### ISSUE TITLE
Slideshow using wrong path on production

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#115]
Slideshow FSM always uses path ct:lesson_read to show each lesson (I just verified it does that correctly in my current master, commit de7b3deb, which is also the current HEAD of raccoongang/master), but the production site is instead using ct:lesson, which erroneously makes slideshows present the question form for each ORCT.  That defeats the whole purpose of a slideshow, which is to present all the lessons simply as "slides" with no question form.  There are two obvious questions:

* when and how did this bug creep into the production version?
* why is the production server running code that diverges from the raccoongang/master branch?

@maxsocl @VladimirFilonov any ideas?

**Comment by maxsocl** [comment]
@cjlee112 Production server running exactly the same version of code as on master.

**Comment by maxsocl** [comment]
@cjlee112 Bug has been fixed. Bug was caused by old slideshow fsm version.

**Comment by maxsocl** [comment]
@cjlee112 Test it please.

**Comment by cjlee112** [comment]
@maxsocl Great!  That fixed it.
