### ISSUE TITLE
Server Error on some Wikipedia concept search results

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#120]
I've occasionally observed a Server Error 500 when clicking on a Wikipedia search result from searching for concepts (on a courselet Concepts tab).  For an example of this, please see the server log for Nov. 28 around noon PST.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367463217489)

**Comment by maxsocl** [comment]
@cjlee112 

The problem is in `Lesson.search_sourceDB` method.
`Structured data analysis` query is ambiguous for wiki and `dataClass.search(query, **kwargs)` returns all pages including [common page for thee possible search results](https://en.wikipedia.org/wiki/Structured_data_analysis)

And when we click on link `/ct/teach/courses/1/units/1/concepts/wikipedia/Structured%2520data%2520analysis/`  we falling in Exception `Key Error` because `wikipedia.page(sourceID)` raises this KeyError:

```pdb
(Pdb) wikipedia.page(sourceID)
*** DisambiguationError: "Structured data analysis" may refer to: 
Structured data analysis (statistics)
Structured data analysis (systems analysis)
Structured data mining
```

So we need to analyze `LessonDoc.search` method and fix it.

**Comment by cjlee112** [comment]
@maxsocl Thanks!  The challenge is that the wikipedia module doesn't give DisambiguationError until you request the page.  It definitely doesn't make sense to try pre-fetching the page for every search result just to see if it will give a DisambiguationError.  If we wait till the user actually requests the page to retrieve it (and then see the DisambiguationError) we are stuck with handling the DisambiguationError in the ct:wikipedia_concept view.  Presumably we would do that by simply displaying the list of disambiguation term options (with links to view them).  We could do something like this:

* define a general DisambiguationError class (to keep this general, rather than tied specifically to wikipedia).

* ct.wikipedia_plugin.LessonDoc.__init__() should handle wikipedia.exceptions.DisambiguationError by raising our new class DisambiguationError with its options attr copied from the wikipedia.exceptions.DisambiguationError object.

* ct.views.wikipedia_concept() should catch that exception, and pass lesson=None, disambiguationOptions=options to pageData.render()

* the ct/wikipedia.html template should handle that case by displaying a table of the disambiguation options (with links to the ct:wikipedia_concept view for each).

**Comment by maxsocl** [comment]
@cjlee112 Great, this is a good plan to handle this issue. I'll implement it in a day.

**Comment by cjlee112** [comment]
@maxsocl Please also add a test for this to the test suite.  thanks!!

**Comment by maxsocl** [comment]
@cjlee112 Sure! But it will be better to add tests to master with approved PR #111 because it has new tests with new structure and it will be annoing to make rebasing again and re-create PR.
