### ISSUE TITLE
Bug:404 page when user clikl on  link "View all FAQs for this lesson"

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#127]
1. Go to https://staging.courselets.org/ct/courses/1/units/1/lessons/2/faq/1/
2. Click on link "View all FAQs for this lesson"

Actual result: Page not found (404) http://prntscr.com/9grjnm
Expected result: New page with  all FAQs for this lessondisplayed.

**Comment by maxsocl** [comment]
➤ Maksym Sokolsky commented:
Duplicate for #150
