### ISSUE TITLE
Feature request: Missing author name when user add question in  FAQ tab

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#128]
1. Go to https://staging.courselets.org/ct/
2. Log in as user ( art.bybluk test1 )
3. Go to https://staging.courselets.org/ct/courses/1/units/1/lessons/2/faq/
4. Post a new question or comment

Actual result:
 Missing author name when user add question in  FAQ tab   http://prntscr.com/9foejj

Expected result: author name is displayed as for the Teacher

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480185788)

**Comment by cmltaWt0** [comment]
Fixed
