### ISSUE TITLE
Feature request: Need to describe and develop rules for viewing user profile page

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#129]
1. Login as user (artbybluk test1)
2. Go to https://staging.courselets.org/ct/courses/1/
3. Click on  "The Teacher"  link

For now we can see empty user profile pae http://prntscr.com/9fo2l7  , because teacher has his own private data, and we dont now is it correct to show this data for student (For example e-mail, etc) .

Need to analyse all user roles that exist in system and set permissions for every role, 
Need to describe what data need to share in user profile page (for Example: nickname, full name, etc.)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480185659)

**Comment by redilonka** [comment]
not fixed
