### ISSUE TITLE
Finalize course creation via LTI hook

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#130]
In our hackathon, we have faculty who want to start using the existing Courselets platform now, so we want to use the fast course-creation mechanism through LTI that was previously discussed, i.e. 

* instructor pastes a general "course creation" link in their class on their university eLearning platform;
* instructor clicks the link and LTI sends the course and instructor info to Courselets;
* if the course does not already exist on Courselets, it is created;
* if the instructor does not have an account on Courselets, it is created, and given instructor role on the course;
* if the course already exists, just redirect to the course page.

We'd like to start using this capability with hackathon participants.

**Comment by maxsocl** [comment]
@cjlee112 
This functionality was implemented and merged in #42 
Docs http://cjlee112.github.io/socraticqs2/lti.html#course-creation-process
But we need to perform double check of this functionality.

**Comment by cjlee112** [comment]
@maxsocl Great.  Since our LTI credentials are already loaded into the UCLA eLearning platform, so let's do some real-world tests there. I'll follow up with details on Slack.
