### ISSUE TITLE
[Courselet] - Search for Concept Error

### ISSUE THREAD

**Issue by Vadimstruk** [cjlee112/socraticqs2#134]
**Screenshot:** http://prntscr.com/a6k26e

**Steps to reproduce:**

1. Go to https://staging.courselets.org/ct/courses/ ( admin / testonly )
2. Go to "Enrolled courses"
3. Click on any Course
4. Click on any Courselet
5. Go to "Concepts" imput
6. At field "Search" enter few gaps ( by pressing Spacebar)
7. Click on "Search" button

**Actual result:** Unknown Error appears http://prntscr.com/a6k26e
**Expected result:** Message "This field can't be blank" should appear

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480184379)

**Comment by maxsocl** [comment]
DoD:
https://github.com/raccoongang/socraticqs2/commit/f21a053da07fa659178c99dd51a7b0f160d105b3

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by maxsocl** [comment]
Need to test

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by maxsocl** [comment]
Fixed

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
f21a053da07fa659178c99dd51a7b0f160d105b3

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
