### ISSUE TITLE
[Courselet] - Create courselet without name

### ISSUE THREAD

**Issue by Vadimstruk** [cjlee112/socraticqs2#135]
**Steps:**

1. Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly )
2. in field "Add a New Courselet - Title" leave some empty field by clicking spacebar
3. click "Add" button 

**Actual result:** Courselet without name is created http://prntscr.com/a6jso0 , http://prntscr.com/a6jsuz
**Expected result:** Message "Courselet title should contain at least 1 symbol" should pop out

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367475710336)

**Comment by maxsocl** [comment]
Duplicate issue #137

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
Fixed
