### ISSUE TITLE
[Concept] - Error occurs after deleting Concept Statement

### ISSUE THREAD

**Issue by Vadimstruk** [cjlee112/socraticqs2#136]
**Screenshot**
1. Go to any Courselet page
2. Open Concepts tab
3. Create a new Concept (e.g. "Test Concept")
4. Go to the new Concept page
5. Open Lessons tab 
6. Create a new Lesson within this Concept (e.g. "Test Lesson")
7. Go to Edit tab of the Concept
8. Press "Delete this Lesson" button (Concept Statement of the Test Concept will be deleted) 
9. Go back to the Courselet page
10. Open Concepts tab. 

**Actual Result: *\* http://prntscr.com/a7c55h
**Expected Result:** The list of Concepts should be displayed

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367478284936)

**Comment by maxsocl** [comment]
DoD:
https://github.com/raccoongang/socraticqs2/commit/39f9c274ae839c4027243f94cc357d73ad7ac8bd

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by maxsocl** [comment]
Fixed - need to test

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
