### ISSUE TITLE
[Bug] It is possible to Create courselet without name

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#137]
**_Steps:**_
- Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly )
- in field "Add a New Courselet - Title" enter few gaps ( by pressing Spacebar)
- click "Add" button

**_Actual result:**_ Courselet without name is created http://prntscr.com/a6jso0 , http://prntscr.com/a6jsuz
**_Expected result**_: Message "Courselet title should contain at least 1 symbol" should pop out

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480185595)

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by cmltaWt0** [comment]
Fixed

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
