### ISSUE TITLE
[Bug] Long Titles breakes layout

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#138]
**_Steps:**_
- Go to https://staging.courselets.org/ct/courses/ ( admin / testonly )
- Go to "Enrolled courses"
- Click on any Course
- In field "Add a New Courselet - Title" enter max length title
- Click "Add" button

**_Actual result:**_ Long Titles breakes page layout http://prntscr.com/a6kbrb , http://prntscr.com/a6kc7b
**_Expected result:**_ Maximum permissible lenght should be set up

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480093145)

**Comment by maxsocl** [comment]
This is frontend bug. Should be fixed in markup.

**Comment by maxsocl** [comment]
Fixed.

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
dda3bed

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
