### ISSUE TITLE
[Bug] Instructor is NOT able to Navigate to the Related Lessons page

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#140]
**_Steps:**_
- Go to https://staging.courselets.org/ct/courses/ ( admin / testonly )
- Go to "enrolled courses"
- Go to any Course
- Create new Courselet
- Go to "Concepts" add new Concept with name "Test"
- Go to "Test" Concept, and open "Concepts" imput
- For Concept "Test" add related Concept With Title "Test for delete"
- Open "Test for delete" in new Browser Imput, and in "Edit" page delete it
- return to "Test" Concept, and click on "Lesson" imput
- return to "Concepts" imput

**_Actual result:**_ error page appears http://prntscr.com/a6v80k
**_Expected result:**_ page should be opened in normal way

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480187973)

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by cmltaWt0** [comment]
74ceef3c67b96fa59d817bc6d3d87bd9027b51f8

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
