### ISSUE TITLE
[Bug] error after Reverse of the relation between Concepts

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#141]
**_Steps:**_
- Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly )
- Add new Courselet
- Click on "Concepts" imput
- Add New Concept with name "Test"
- Go to the "Test" Concept
- Go to Concepts imput
- Add one Related Concept with name "Test2"
- Open "Test2" in new window, and delete this Concept
- Go back to "Test" Concept window, and click on "Reverse" button

**_Actual result:**_ http://prntscr.com/a6vxsk
**_Expected result:**_ message "This Concept is deleted" should appear

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480183993)

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by cmltaWt0** [comment]
8be7dc756ca8f0bb04763445584a6d3848658124
