### ISSUE TITLE
[Bug] KeyError after Clicking on Search result Concept from Wikipedia

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#142]
***Steps:***
* Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly )
* Click on any Courselet
* Go to "Concepts" imput
* In field "Search" type  "AAA" ( "CCC" ), an click "Search" button
* Click on "AAA" Concept ( from Wikipedia DB ) in search result

***Actual result:*** error appears http://prntscr.com/a6xdmx
***Expected result:*** User is able to Add/Navigate any Concept from Search Result

**Comment by maxsocl** [comment]
Duplicate issue #120

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]
