### ISSUE TITLE
[Bug] Lesson is added after refreshing page

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#143]
**_Steps:**_
- Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly ) ( Google Chrome)
- Go to any Courselet
- Go to "Concepts" imput, and click on any Concept
- Fill all required fields with valid data, and press 'Add' button
- Click "refresh" button of your browser, and "Continue" button in pop-out window http://prntscr.com/a6xktx

**_Actual result:**_ Lesson will be added again http://prntscr.com/a6xkyc
**_Expected result:**_ Lesson shoud be added only after pressing "Add" button

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480095644)

**Comment by maxsocl** [comment]
This is conceptual issue - need to return HttpResponseRedirect instead of simple HttpResponse but it will lead to changes in hole flow - need to completely change this flow and I believe we will do it in HackUI.

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]
