### ISSUE TITLE
[Bug] 404 error after navigation to deleted lesson

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#144]
**_Steps:**_
- Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly )
- Go to any Courselet
- Go to any Course from the list
- Go to "Lessons" imput, and create lesson "Test"
- Open "Test" lesson in new tab, and delete it
- Try to Navigate to "Test" lesson from "Lessons" imput

**_Actual result:**_ 404 error http://prntscr.com/a6y1lh
**_Expected result:**_ Message "This lesson is deleted" should appaer

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480096989)

**Comment by maxsocl** [comment]
404 is a normal response is case of any resource absence.
And if I will delete previously existent Lesson I can't distinguish where searched Lesson (by id) was deleted or never exists.
So I have added custom 404 and 500 templates to show for user.

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by maxsocl** [comment]
DoD:
https://github.com/raccoongang/socraticqs2/commit/625fa7783b732825e861a39a4899275af27148bd

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by maxsocl** [comment]
Fixed - need to test.

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
625fa7783b732825e861a39a4899275af27148bd

**Comment by redilonka** [comment]
@cmltaWt0 please merge your fix to development

**Comment by redilonka** [comment]
We need just add fix into project ()

**Comment by cmltaWt0** [comment]
404 and 500 templates are based on OLD UI. Let's do it using the new UI template.
I'm going to close the issue and add the new conversation in the notion.
