### ISSUE TITLE
[Bug] Long descriptions affects loading speed

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#146]
**_Steps:**_
- go to https://staging.courselets.org/ct/teach/courses/1/
- Go to "Edit imput"
- In field "Description" enter text with lenght >1500 symbols

**_Actual result:**_ Page Stops responding http://prntscr.com/a6yvqw
**_Expected result:**_ page works fluently. Maximu lenght for Description and Title should be set up.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480095708)

**Comment by maxsocl** [comment]
Fixed - need to test

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
d84d8fc282bfd6e4fd2024bd65db88f3fa55b664

**Comment by redilonka** [comment]
@cmltaWt0 please merge your fix to development

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
