### ISSUE TITLE
[Bug] Cannot Sign up with Facebook account

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#147]
**Steps to reproduce:**
1. Go to https://staging.courselets.org/login/ 
2. Click Sign in with Facebook button
**Actual result**: http://prntscr.com/a3z8qb
**Expected result:** user can Sign up with Facebook acc

**Comment by maxsocl** [comment]
@artbybluk Social auth applications excepts twitter and khanacademy was never configured for staging.courselets.org
