### ISSUE TITLE
[Bug] System message breaks layout

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#149]
**Steps:**
Go to https://staging.courselets.org/ct/courses/ ( admin / testonly )
Go to "Enrolled courses"
Click on any Course
Go to "Lessons" imput
Click on Search button
**Actual result**: http://prntscr.com/aa6pec
**Expected result:** Fields and messages should be on the same level

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480095837)

**Comment by maxsocl** [comment]
Markup bug.

**Comment by maxsocl** [comment]
Fixed - need to test

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
99ce7827078e2ea125989c7627022ef4b1795f41

**Comment by redilonka** [comment]
fixed in Tagged release v1.7.0
