### ISSUE TITLE
[Bug] 404 error after returning to FAQ page

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#150]
**Steps:**
Go to https://staging.courselets.org/ct/courses/ ( admin / testonly )
Go to "Enrolled courses"
Click on any Course
Go to "Concepts" imput
Click on any Concept
Go to "FAQ" imput
Click on existing ( or create new one) Discussion
Click on "View all FAQs for this lesson" button http://prntscr.com/aa72me
**Actual result:** Error page http://prntscr.com/aa72ry
**Expected result:** User is redirected to the FAQ page

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138365922713674)

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by cmltaWt0** [comment]
Fixed.
