### ISSUE TITLE
[Bug] Long search value error

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#152]
**Steps:**
Go to https://staging.courselets.org/ct/teach/courses/2/units/32/errors/349/ ( admin \ testonly)
In field "Search for containing" enter long text ( >300 symbols )
Click "Search" button
**Actual result:** 414 error http://prntscr.com/aa7drd
**Expected result:** Maximum permissible lenght should be set up

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480094361)

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by cmltaWt0** [comment]
276dc3c2c7b4ddd62229028cdb76149c732ae89f

**Comment by redilonka** [comment]
please merge your fix to development
