### ISSUE TITLE
[Bug] Error after manual adress entering

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#153]
**Steps:**
Go to https://staging.courselets.org/ct/teach/courses/1/
In adress line change "1" to "5"
Click "Enter"
**Actual result:** error http://prntscr.com/aa7zem
**Expected result:** Message "You have no access to this Course" should appear

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367177804992)

**Comment by maxsocl** [comment]
@artbybluk Fixed and can  be tested on-demand on dev.courselets.org (need to switch to https://github.com/raccoongang/socraticqs2/commits/fix_issue%23153 branch)

**Comment by cmltaWt0** [comment]
3870e747630e78f8056ee50a48ad42002b93a870
