### ISSUE TITLE
[Bug] No system messages

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#154]
**Steps:**
Go to https://staging.courselets.org/ct/courses/ ( admin / testonly )
Go to "Enrolled courses"
Click on any Course
Go to Any Courselet
Go to "Lessons" imput, and click on any Lesson
Go to "Error" imput
In "Search" field enter name of Not existing Lesson in CourseletDB
Click "Search" button
**Actual result:** no system message appears http://prntscr.com/aa85ja
**Expected result:** Instructor is able to See System Messages that reflect the result validation process

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480398882)

**Comment by maxsocl** [comment]
@artbybluk Fixed and can be re-tested on demand on dev.courselets.org (I need to switch to branch https://github.com/raccoongang/socraticqs2/tree/fix_issue%23154)

**Comment by cmltaWt0** [comment]
fe9bc7830128014687434a5a4239d36493d4b413
