### ISSUE TITLE
[Bug] System displays wrong search results

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#156]
*Steps:*
* Go to https://staging.courselets.org/ct/teach/courses/1/ ( admin / testonly )
* Go to any Course
* Click on any Lesson
* Go to "Errors" imput
* In search field type " x ", and click "Search" button

*Actual result:* http://prntscr.com/ab13sh
*Expected result:* System shall display search results which titles partialy coincide with the value Instructor entered

**Comment by maxsocl** [comment]
@artbybluk This is a correct result - search looking not only to title but also to text.

**Comment by maxsocl** [comment]
@artbybluk what about this issue? Code return results as expected (by title and by text). Can we close this issue?

**Comment by artbybluk** [comment]
not a bug
