### ISSUE TITLE
[BUG] Buttons are blurry

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#159]
_Steps:_
- Go to https://staging.courselets.org/chat/enrollcode/49b0f7a4357842b094d2bf4244a72b91/
- Log in with existing account
- Set you cursor to button and move it away

_Actual result:_ button is blurry http://prntscr.com/b042ze
_Expected result:_ http://prntscr.com/b042ux

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367130265008)

**Comment by maxsocl** [comment]
Frontend bug
#158

**Comment by maxsocl** [comment]
@artbybluk Can't reproduce bug.

**Comment by artbybluk** [comment]
@maxsocl not reproducible on Mac OS. Bug is on Windows OS

**Comment by cmltaWt0** [comment]
@redilonka please check this.

**Comment by cmltaWt0** [comment]
Stale issue - current Chat UI has no Lets get started button.
