### ISSUE TITLE
[BUG] Full screen mode returns to the begining of the course

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#160]
*Steps:*
- Go to https://staging.courselets.org/chat/enrollcode/49b0f7a4357842b094d2bf4244a72b91/
- Log in as to the system ( qa_olodymyr / qa_olodymyr )
- Pass about 35 % of the course
- Go to Fullscreen mode

*Actual result:* Student resumed to the start of the lesson
*Expected result:* User stays on the same position

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
verified
