### ISSUE TITLE
[BUG] Wrong button icon

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#161]
*Steps:*
- Go to https://staging.courselets.org/chat/enrollcode/49b0f7a4357842b094d2bf4244a72b91/
- Log in as to the system ( qa_olodymyr / qa_olodymyr )
- Pass full course til the end keeping sidebar closed

*Actual result:* http://prntscr.com/ay97hd , http://prntscr.com/ay97nb
*Expected result:* http://prntscr.com/ay996n , http://prntscr.com/ay99at

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
I can't reproduce this bug in Safari:

http://prnt.sc/b2po5i
http://prnt.sc/b2poh6

**Comment by artbybluk** [comment]
Updated description

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
verified
