### ISSUE TITLE
[BUG] Corselet images are not saved after creating

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#162]
*Steps:*
- Go to https://staging.courselets.org/ct/teach/courses/1/
- In Field "Title" type any valid name
- In Fields "Img URL" and "Small img URL" paste valid urls for the images
- Click "Add" button
- Go to "Edit" input

*Actual result:* URLs for images where not saved http://prntscr.com/ay9sa3
*Expected result:* URLs for images where saved

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
Verified
