### ISSUE TITLE
[BUG] User is able to add same lesson few times

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#163]
*Steps:*
- Go to https://staging.courselets.org/ct/teach/courses/1/
- Add new Courselet
- Go to "Lessons" input
- Search for - Independence (probability theory) and ADD it
- Search for - Independence (probability theory) and try to add it again

*Actual result:* User is able to add the same Lesson few times http://prntscr.com/ay9w2e
*Expected result:* User is NOT able to add same Lesson few times

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
This is a current behaviour of courselets core.
There is the PR #122 that improve Lesson searching/adding UI - it provides different Lesson versions to choose. I need to review this PR again but I believe this PR remove Lesson from search if we already add one.
