### ISSUE TITLE
[ENHANCEMENT] Updated Courselet dosent display new Lessons for student

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#164]
_Steps:_
- Go to https://staging.courselets.org/ct/teach/courses/1/
- Add new Courselet
- Add 2 lessons for new courselet
- Go to "Edit" input and follow this URL http://prntscr.com/ay9gw6
- Finish Courselet for 100%
- Return to Courselet details and add 2 more lessons
- Go again to this URL http://prntscr.com/ay9gw6 and try to pass this Courselet again

_Actual result:_ User can`t see 2 new lessons http://prntscr.com/ay9ju9
_Expected result:_ User is able to see all lessons

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480094297)

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
@artbybluk there is no specification for such behaviour. FSM is not intended to handle this case.
And I think that when Course released this is very bad to add Lesson in the middle of the sequence.
This is the same as to ass new Chapter to a Book when I finished the Book already.

**Comment by cmltaWt0** [comment]
Fixed but need a future refinement
