### ISSUE TITLE
[BUG] Broken layout in fullscreen mode on IE 

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#166]
_Steps:_
- Go to https://staging.courselets.org/chat/enrollcode/49b0f7a4357842b094d2bf4244a72b91/ **on IE 11**
- Log in with existing profile
- Go to fullscreen mode

_Actual result:_  Broken layout http://prntscr.com/b04a1d
_Expected result:_ everything  is working in the right way

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480094425)

**Comment by maxsocl** [comment]
Frontend bug
#158
