### ISSUE TITLE
[BUG] Button "Continue" missing between lessons

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#167]
*Steps:*
- Go to https://staging.courselets.org/chat/enrollcode/195fdebc66bb412a9d9fe43bbbed4b04/
- Login with existing profile
- Click on "Let`s Get Started" button

*Actual result:* system open 3 first lessons at once, without pressing "Continue: button http://prntscr.com/b2ddlk
*Expected result:* User should press "Continue" button after each lesson

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
Note: to test you need to login w/ Course Instructor user.

**Comment by maxsocl** [comment]
Note 2: `Continue` button is missed only between similar Lessons - such base explanation and log explanation.
Will be fixed.

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
Verified

**Comment by maxsocl** [comment]
@artbybluk need to test this again - I have added code related for this feature.
