### ISSUE TITLE
[BUG] User is able to open link from "unpublished course"

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#168]
*Steps:*
- Go to https://staging.courselets.org/ct/teach/courses/1/
- Click on any courselet wich is "Not yet published"
- Go to "Edit" input
- Go to this URL http://prntscr.com/ay9caa

*Actual result:* User is able to start courselet
*Expected result:* User is NOT able to start courselet

**Comment by maxsocl** [comment]
#158 
We need a clarification here - only Instructors can access unpublished courselets.

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
Verified
