### ISSUE TITLE
[BUG] Wrong pagepage reposition after clicking on sidebar Resource name

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#169]
*Steps:* 
- Go to https://staging.courselets.org/chat/enrollcode/49b0f7a4357842b094d2bf4244a72b91/
- Login with existing profile
- Finish Courselet for 100%
- On sidebar click at "Concept inventory" or "Scientific misconceptions"

*Actual result:* name of the lesson is NOT visible http://prntscr.com/b2re7o
*Expected result:* http://prntscr.com/b2rf31

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
verified
