### ISSUE TITLE
Bad URL for concept FAQ

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#17]
concepts/46/faq/143/ page generates (View all FAQs for this lesson) link to concepts/46/lessons/faq/
instead of concepts/46/faq/ as it should.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367467594690)

**Comment by maxsocl** [comment]
Fixed in 9b7ef1ddf58a0d19670fd60970b0b0843906defb  for issue #150
