### ISSUE TITLE
[BUG] Button "Close" appears when Courselet have only 1 lesson

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#172]
*Steps:* 
- Go to https://staging.courselets.org/chat/enrollcode/44cdc71e1ebd48c9b1af111c3c8cca24/
- Login with existing profile
- Finish Courselet fo 100%

*Actual result:* Button "Close" appears http://prntscr.com/b2s1fi
*Expected result:* Button "Close" doesn`t appear

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
Verified
