### ISSUE TITLE
[BUG] Wrong order of the resources in Chat

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#173]
*Steps:*
- Go to https://staging.courselets.org/chat/enrollcode/5b389dbeab3a4b2ca4e32854c295b9b7/
- Login with existing profile
- Pass courselet for 100%
- Click on Resources in this way http://prntscr.com/b347c0

*Actual result:* Resources will be displayed in Chat in the same order
*Expected result:* Resorces should be displayed in Chat all the time in order which shown in sidebar http://prntscr.com/b348sa

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
@cjlee112 What should we follow to return Resources?

**Comment by maxsocl** [comment]
@artbybluk now Resources are sorted by title in alphabetical order
