### ISSUE TITLE
[BUG] Wrong order of the ERROR modules

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#174]
*Steps:*
- Go to https://staging.courselets.org/chat/enrollcode/93d1b31b884542c58653e367a49391fa/
- Login with existing profile
- Answer for the first question and click on "Different" button
- Select "ERROR ORDER TEST" and click "Continue"
- press "Still confused, need help" until error  modules will end

*Actual result:* Resolutions are displayed in wrong order http://prntscr.com/b35bz0
*Expected result:* Resolutions displayed in right way

**Comment by maxsocl** [comment]
#158

**Comment by maxsocl** [comment]
But there are Resolves not Errors.

**Comment by maxsocl** [comment]
@artbybluk Fixed

**Comment by artbybluk** [comment]
verified
