### ISSUE TITLE
[BUG] Chat doesn`t show video added to error module

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#175]
*Steps:*
- Go to https://staging.courselets.org/ct/teach/courses/1/units/13/errors/203/
- Add new lesson ( in field "Delivery medium" select - video; in field "Url" - enter url for any video from YouTube )
- Then go to https://staging.courselets.org/chat/enrollcode/93d1b31b884542c58653e367a49391fa/
- Answer for the first question and click on "Different" button
- Select "ERROR ORDER TEST" and click "Continue"
- press "Still confused, need help" until error  modules will end

*Actual result:* system doesn't displayed video
*Expected result:* system displayed video

**Comment by maxsocl** [comment]
#158 
@artbybluk this case was not considered for MVP.

**Comment by maxsocl** [comment]
@cjlee112 Do we need to implement Video rendering for Error resolutions?
