### ISSUE TITLE
Fix Long Titles breakes layout #138

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#181]
https://github.com/cjlee112/socraticqs2/issues/138

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138308180149322)

**Comment by maxsocl** [comment]
DoD:
https://github.com/raccoongang/socraticqs2/commit/dda3bedf58c88e3a9bdc311b13255657660bb5ea

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]

**Comment by cmltaWt0** [comment]
dda3bedf58c88e3a9bdc311b13255657660bb5ea
