### ISSUE TITLE
Fix Instructor is NOT able to Navigate to the Related Lessons page #140

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#182]
https://github.com/cjlee112/socraticqs2/issues/140

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138308180149326)

**Comment by maxsocl** [comment]
DoD:
https://github.com/raccoongang/socraticqs2/commit/74ceef3c67b96fa59d817bc6d3d87bd9027b51f8

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]
