### ISSUE TITLE
Fix error after Reverse of the relation between Concepts #141

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#183]
https://github.com/cjlee112/socraticqs2/issues/141

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138308180149330)

**Comment by maxsocl** [comment]
DoD:
https://github.com/raccoongang/socraticqs2/commit/8be7dc756ca8f0bb04763445584a6d3848658124

[--- Commented from Asana.com
#commenter Maksym Sokolsky
---[aa]
