### ISSUE TITLE
Need a mechanism for moving lessons along with their student data

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#19]
Example: say I decide a courselet is too long and want to split it in two.  If students have already entered answers etc. for a given lesson, I want all that data to come along when I move the lesson to a new courselet.  Our schema can do this easily: keep its existing UnitLesson, just re-attach it to the new Unit.  The only question is the UI.  One option is to add a Move button on the Edit tab for the lesson: you would pick from a list of other courselets in the current course.  I guess that's adequate for the moment.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367465931856)

**Comment by maxsocl** [comment]
@cjlee112 are we still need this?
I have the code for this UI and simply can merge it.

**Comment by maxsocl** [comment]
Decided to merge into master.

**Comment by cmltaWt0** [comment]
Done
