### ISSUE TITLE
Need JSON response data for any Course

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#193]
Since we currently lack UI for downloading response data, I again need a JSON dump of Response data for course 17, exactly as Maksim did it last time...

Spec
===
Responses
---

Hi Maksim,
I'm writing to let you know that early next week I'd like to get a
one-time data dump of ORCT Response counts for each student in my course
(Courselets course_id=5).  I need these for grading purposes (i.e. we
give students credit for completing the assigned exercises, so I need to
know how many exercises each student did).  Here are the specifics:

* I think the easiest format for me to process would be JSON, in the
basic form of a list of dicts, where each dict represents one student
response.

* For each student response, I'd like to have: user_id, whatever name or
LTI identity info you've got (so I can match the student to the
registrar record for grades; best is the student ID number if LTI
supplied that), response_id, response.text, confidence, selfeval,
status, unitlesson_id, unit_id.

* the response set should be filtered to only contain those that 1. are
in my course; 2. response.kind == 'orct'; and 3. are for UnitLessons
with non-NULL order value (these represent lessons that were actually
assigned).

Do you foresee any difficulties in doing this?  In the future we can add
UI for such reports, but for the moment I think a one-time data dump is
the easiest path.

Thanks!!

Student Errors
---

Hi Maksim,
as a next step in analyzing the student data from Courselets, I'd like
to get a data dump of StudentError data (with associated error model
data), in more or less the same JSON format as we used for the last data
dump.  This is mainly for Courselets course_id=5, but I guess we might
as well again set this up as a general API capability.  Proposed details:

* for each StudentError, I'd like to have a dict of: response_id (for
matching up with the Response data you already gave me), status, atime,
author_id, errorModel_id.

* for each UnitLesson of kind=='erromod': id (to match it to
StudentError.errorModel_id); lesson.concept_id; lesson.concept.isAbort;
lesson.concept.isFail; lesson.text; treeID.

What do you think?

Details
---

Authentication is required for this API.

It can be tested on following links:
https://staging.courselets.org/api/v0/courses/1/responses/ => Course id=1 report
https://staging.courselets.org/api/v0/courses/1/errors/ => Course id=1 errors

Additional question I want to ask is about LTI identity - currently I add LTIUser.user_id as lti_identity field.

What identity you want? I can add DjangoUser username or lis_person_name_full or lis_person_sourcedid. So if you want some id to be added to results - there are Django user id as author_id or LTIUser user_id as lti_identity. If you want some readable name to be added - I can add DjangoUser username and LTIUser some_name_from_lti.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/202671289207865)

**Comment by maxsocl** [comment]
For this I will add ability to get Course reports via API

**Comment by maxsocl** [comment]
I've rebased old branch `course_report_api` and open new PR #209 
Old PR was #125

**Comment by maxsocl** [comment]
@redilonka versions added but not as you proposed - starting from v0.

**Comment by maxsocl** [comment]
How to check:

```queryset = Response.objects.filter(kind='orct', unitLesson__order__isnull=False, course__id=<course_id>)```

**Comment by cjlee112** [comment]
If we are expanding this issue to a general feature we should change the issue title (max completed the course 17 data dump last year!).

**Comment by maxsocl** [comment]
We need to specify access restrictions.

**Comment by maxsocl** [comment]
Only Course creator can access this API.
