### ISSUE TITLE
admin 504 error for viewing a Response

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#195]
Try to view a Response in the admin interface, e.g. https://www.courselets.org/admin/ct/response/15539/

Just gives a 504 gateway error.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/202671972058226)

**Comment by alexbojko** [comment]
I have an idea about this issue.
We should try to do this:
`uwsgi_read_timeout 300; # or even more than 300.`

in our nginx.conf file.

I found it [here](http://stackoverflow.com/questions/16141610/nginx-timeouts-when-uwsgi-takes-long-to-process-request)

**Comment by maxsocl** [comment]
Issue was fixed by setting `uwsgi_read_timeout 120;`
But we need to change Django Admin config for `StudentError` and `Response` models to use `raw_id_fields` attribute.
https://docs.djangoproject.com/en/1.7/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields

**Comment by maxsocl** [comment]
I will add this to master.

**Comment by maxsocl** [comment]
Fixed in https://github.com/cjlee112/socraticqs2/pull/214
