### ISSUE TITLE
ChatUI answer should require click to Submit

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#199]
Students are accidentally submitting incomplete answers by typing Enter.  For the moment, we should just prevent Enter from submitting their answer; only clicking the Submit button should submit their answer.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/204801385737213)

**Comment by maxsocl** [comment]
@cjlee112 Are you want me to fix this in current Chat implementation or to be available in LiveSession feature?
