### ISSUE TITLE
Fix Resources links

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#202]
@karluxd

After latest changes for JS links for Resources are disappeared.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/224288594947789)

**Comment by maxsocl** [comment]
<img width="526" alt="screen shot 2016-11-25 at 2 17 05 pm" src="https://cloud.githubusercontent.com/assets/877401/20625130/f069416e-b319-11e6-94aa-5ec55b5e9248.png">

**Comment by maxsocl** [comment]
@karluxd

I've tried to find "wrong" commit and everything works before you commit 43c0b1d206b54551bc7ed1c256b7037082ce1ce2

Can you make a quick look at this commit because I cant find something very quickly?

<img width="1280" alt="screen shot 2016-12-19 at 1 33 57 pm" src="https://cloud.githubusercontent.com/assets/877401/21311579/90707072-c5f0-11e6-8a03-8f58b7e7442c.png">
<img width="1280" alt="screen shot 2016-12-19 at 1 33 27 pm" src="https://cloud.githubusercontent.com/assets/877401/21311580/909ae2c6-c5f0-11e6-9c26-fe4ef8bb2983.png">

**Comment by redilonka** [comment]
fixed
