### ISSUE TITLE
Add template for Course

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#203]
Add template for Course

Course template should contains:

1. Join Live Session link if Live session started by Instructor
2. Section for Courselets
3. Section for Live Session history
4. Course Image
5. Course title
6. Instructor avatar
7. For current Live Session - text "<INSTRUCTOR_NAME> has started a new live session in <COURSE_TITLE>."
8 . Course Author/Instructor name

https://marvelapp.com/iedi87
https://marvelapp.com/iedi87/screen/15848406

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/224288594954086)

**Comment by redilonka** [comment]
where is course descriptions?

**Comment by redilonka** [comment]
@maxsocl 
1) I see instructor title on the course page. Is it ok?
2) Also, I don't see estimated time and amount lessons in courselets. 
3) Containers must have bottom padding on the courselets page `(id="courselets" class="course-content-units") `
4) Should logotype be clickable?
5) Live sessions which ended should have year
6) add hint "No prerequisites" when we don't have links what students can learn and know on the lesson page
7) I think if we have time in live chat we should add this to the history live session page
8) add bottom padding on the history live session page `class="description container"`

**Comment by maxsocl** [comment]
@redilonka 

1. it is ok. But I need to understand what to do w/ another instructors.
2. Fixed
3. Fixed
4. There is no spec for this
5. Fixed
6. Fixed
7. Fixed
8. Fixed
