### ISSUE TITLE
Remove `Resources` title from sidebar when there are not resources available

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#221]
@karluxd

**Comment by karluxd** [comment]
@maxsocl I've already completed my dev milestone. I can discuss it with Chris tomorrow if you need me for ongoing development work. Someone else has added the resources to the sidebar, so maybe that same person could add the logic for this?

**Comment by alexbojko** [comment]
fixed in feature/live_hide_resources_header_if_live branch
