### ISSUE TITLE
Remove duplicated Live session button

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#234]
In `/ct/` page.
Join links generated for each user Role regardless of Role's type.
Need to generate Join invite only for Student Role.

**Comment by maxsocl** [comment]
Do we want to generate Loin link only for Student role?

**Comment by maxsocl** [comment]
So does User have an ability to Join to Live Session w/ Instructor only Role?

**Comment by maxsocl** [comment]
@cjlee112

**Comment by maxsocl** [comment]
Decided to live Join button only for Student Role.

**Comment by alexbojko** [comment]
fixed and pushed to branch fix/issue#234
