### ISSUE TITLE
Loading example data is not working

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#24]
When I try to load example data to fresh db I get an error:
```bash
(env)user@home:~/code/socraticqs2/mysite$ python manage.py migrate

Operations to perform:
  Synchronize unmigrated apps: crispy_forms
  Apply all migrations: sessions, admin, sites, auth, contenttypes, ct
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying ct.0001_initial... OK
  Applying ct.0002_auto_20141110_1820... OK
  Applying ct.0003_auto_20141110_2153... OK
  Applying ct.0004_auto_20141117_2208... OK
  Applying ct.0005_unitstatus... OK
  Applying ct.0006_courseunit_releasetime... OK
  Applying ct.0007_auto_20150112_1604... OK
  Applying ct.0008_auto_20150120_1407... OK
  Applying ct.0009_auto_20150127_1752... OK
  Applying ct.0010_auto_20150129_1209... OK
  Applying ct.0011_auto_20150129_1209... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK

(env)user@home:~/code/socraticqs2/mysite$ python manage.py loaddata dumpdata/debug.json

django.db.utils.IntegrityError: Problem installing fixture '/home/user/code/socraticqs2/mysite/dumpdata/debug.json': Could not load contenttypes.ContentType(pk=17): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model
```
:confused:

**Comment by cjlee112** [comment]
please try the new debug-e.json file added in commit 1dbb23b

**Comment by maxsocl** [comment]
Fix tested. Thanks!

**Comment by cjlee112** [comment]
For the record, the solution was to run `python manage.py dumpdata -e contenttypes >dumpdata/debug-e.json`

**Comment by rcdosado** [comment]
after i've done what @cjlee112 has instructed and using loaddata i got this hair raising error (my database has been flushed after dumping), im using django 1.11

> django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'auth_permission' with primary key '61' has an inval
id foreign key: auth_permission.content_type_id contains a value '21' that does not have a corresponding value in django_content_t
ype.id.
is there any workaround for this django version?

**Comment by rimikt** [comment]
@rcdosado Project will be migrate to latest Django version soon.
Also I can't relate your issue with Django version.
Did you overcome Exception `AttributeError: 'Manager' object has no attribute '_inherited'` ?

**Comment by rimikt** [comment]
Also, do you use this command: `./manage.py loaddata dumpdata/debug-wo-fsm.json`

**Comment by rcdosado** [comment]
yes i did, and i'm still having errors, i guess i have to manually edit the database value myself.  thanks anyways!

**Comment by rubenanapu** [comment]
Today (**24th, April, 2020**) I had a similar problem with **Django 2.2** 

My fixtures file was as simple as this:

```
[
{
    "model": "contenttypes.contenttype",
    "pk": 1,
    "fields": {
        "app_label": "admin",
        "model": "logentry"
    }
},
{
    "model": "contenttypes.contenttype",
    "pk": 2,
    "fields": {
        "app_label": "auth",
        "model": "permission"
    }
}]
```

When I ran `./manage.py loaddata initial_data.json`, I got:

`
django.db.utils.IntegrityError: Problem installing fixture '/home/user/reponame/projectname/initial_data.json': Could not load contenttypes.ContentType(pk=2): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model
`

What I did to make it work was just rename the `pk` to `id` for the `contenttypes.contenttype` model. After that, the migration worked as expected.

```
./manage.py loaddata initial_data.json 
Installed 2 object(s) from 1 fixture(s)
```

After the change, my `initial_data.json` file was:

```
[
{
    "model": "contenttypes.contenttype",
    "id": 1,
    "fields": {
        "app_label": "admin",
        "model": "logentry"
    }
},
{
    "model": "contenttypes.contenttype",
    "id": 2,
    "fields": {
        "app_label": "auth",
        "model": "permission"
    }
}]
```

It is worth mentioning that my original **initial_dataj.json** has many other models, but renaming **pk** to **id** only for the `contenttypes.contenttype` solved my problem.

**Comment by cmltaWt0** [comment]
@rubenanapu I've updated master branch.
Actually we don't need contenttypes in a fixture at all.
I updated `debug-wo-fsm.json` fixture to remove contenttype entities.

**Comment by cmltaWt0** [comment]
@rubenanapu 
Probably it's confusing naming. We don't use `initial_data.json`.
I'll rename all fixtures to be more precise in naming.
Meantime please look at Makefile.
```
make .load-fixtures
```
This will do exactly what you need.
