### ISSUE TITLE
[2] Handle `MultipleObjectsReturned: get() returned more than one Role -- it returned 2!` bug when trying to `get_or_create` Student Role for LTI session ()

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#255]
Bug can be reproduced if one manually create duplicated Role's for user in admin page.

Need to fix this.

STR: 
1. Create two roles (FE: student) for the same user in admin

**Comment by alexbojko** [comment]
could you please provide me with step by step how to reproduce it?

**Comment by alexbojko** [comment]
fixed https://github.com/cjlee112/socraticqs2/pull/286

**Comment by DenisKolesnik** [comment]
The issue has been fixed on staging
