### ISSUE TITLE
As a Student I want to have an ability to redo any Lessons in Courselets any time I want

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#257]

**Comment by alexbojko** [comment]
even when you are in the middle of another one courslet?

**Comment by alexbojko** [comment]
when I'm in the corslet what should I do to change my answer for current question?

**Comment by maxsocl** [comment]
> even when you are in the middle of another one courslet?

Yes. To do this one need to open appropriate chat and redo some lesson.

**Comment by maxsocl** [comment]
> when I'm in the corslet what should I do to change my answer for current question?

TBD

**Comment by cmltaWt0** [comment]
Done by adding history and new session button
