### ISSUE TITLE
[2] As a Student I want to see all Historical chats for Courselets ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#258]

**Comment by alexbojko** [comment]
as far as I understand, we should implement it for all chats (live and not live sessions)? 
PS: It would be easy for us to not to split logic between is_live and offline sessions.

**Comment by maxsocl** [comment]
@alexbojko yes and no, we need to separate live and not live history

**Comment by alexbojko** [comment]
fixed and pushed o branch fix/redo_courslet_tests
added test for this, but I faced with a problem that in tests all chats which were created in tests has no state and the state come to the end node once chat created.

**Comment by maxsocl** [comment]
@alexbojko are you fixed 404 I mentioned?

**Comment by alexbojko** [comment]
adding tests for corslet history page

**Comment by DenisKolesnik** [comment]
#452

**Comment by DenisKolesnik** [comment]
#450

**Comment by DenisKolesnik** [comment]
progress bar for live session history doesn't work for now
