### ISSUE TITLE
[2] Redo published courslets ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#259]
As a student I want to have an ability to REDO any published Courselet

**Comment by alexbojko** [comment]
it looks like this ticket duplicates with ticket #257, Am I right?

**Comment by maxsocl** [comment]
@alexbojko No

**Comment by maxsocl** [comment]
Related to #258

**Comment by DenisKolesnik** [comment]
A courselet can be completed again and all answers will be overwritten
