### ISSUE TITLE
Render Forbidden error template instead of raise Key error `KeyError: 'user not in this class'`

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#261]
Need to show some error page for user

Steps to reproduce:
1. Ensure that you have no Role for some Course
2. Open some Lesson in Course directly or open Course directly

**Comment by alexbojko** [comment]
fixed, tested and pushed to branch fix/issue#261
now it will show default error message page with message that this action is not allowed for this user.

**Comment by alexbojko** [comment]
https://github.com/cjlee112/socraticqs2/pull/275

**Comment by maxsocl** [comment]
Note for @maxsocl - need to double check this and fix tests.
