### ISSUE TITLE
As a Student I want to see resolutions for my ErrorModels dynamically appeared in sidebar

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#266]

**Comment by alexbojko** [comment]
what does it mean resolution for error models in this context?

**Comment by maxsocl** [comment]
@alexbojko It means exactly Resolutions for chosen EM's.
<img width="515" alt="screen shot 2017-01-26 at 8 45 44 am" src="https://cloud.githubusercontent.com/assets/877401/22322324/dec41b86-e3a3-11e6-9ca6-4a562ff669b0.png">
