### ISSUE TITLE
[2] As a Student I do not want to see History Live Session w/o any Lessons completed ()

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#267]
Need to filter blank Live Sessions

**Comment by alexbojko** [comment]
fixed and pushed to branch fix/redo_courslet_tests because this task was done in scope of this branch. look PR https://github.com/cjlee112/socraticqs2/pull/270

**Comment by alexbojko** [comment]
pls note that plan chats will be deleted ( I don't think  we have to store them as well as they really harm)

**Comment by maxsocl** [comment]
@alexbojko 👍

**Comment by DenisKolesnik** [comment]
The live session list is empty if there isn't any sessions completed.
