### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#289]
This is where you log in to your Web - Instructor App account.
https://dev.courselets.org/new_login/

It contains:
* Buttons to log in with various social accounts such as Facebook and Twitter.
* A form where the user can log in using an email and a password.
    It contains these fields:

        Email
        Password
        Links to 5.1 Forgot Password and 4. Sign Up.
        The user is redirected to 1. Courses

**Comment by alexbojko** [comment]
fixed and pushed to branch feature/issue#289, added search by SecondaryEmail.

**Comment by DenisKolesnik** [comment]
https://github.com/cjlee112/socraticqs2/issues/391

**Comment by DenisKolesnik** [comment]
https://github.com/cjlee112/socraticqs2/issues/392

**Comment by DenisKolesnik** [comment]
https://github.com/cjlee112/socraticqs2/issues/393
