### ISSUE TITLE
Confirm Email

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#290]
You see this page when you've created an account with an email and a password.

It contains:
* Instructions to click on the link in the confirmation email.
* A link that sends the email again.
* A button that takes you back to the signup form.
* The link in the email redirects to 1. Courses

https://karluxd.atlassian.net/wiki/display/COUR/4.1+Confirm+Email

**Comment by DenisKolesnik** [comment]
The old page appears instead of the new page
