### ISSUE TITLE
New password

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#291]
This is where you create a new password for your account when you reset your password. The reset email links here. The page contains:
A form where the user enters his new password twice.
The form logs in in the user and sends him to 1. Courses

https://karluxd.atlassian.net/wiki/display/COUR/5.2+New+Password

**Comment by DenisKolesnik** [comment]
Te link to the page is missed

**Comment by alexbojko** [comment]
already implemented in scope of ticket #392 
once user send reset password request hi will receive email with the link, going in this link he will be on page New password.
