### ISSUE TITLE
Sign up and Log in Through LTI

### ISSUE THREAD

**Issue by rimikt** [cjlee112/socraticqs2#295]
If their platform is connected, instructors can create an account directly from their LTI platform.

The link would automatically create their account and name their first course before the instructor is redirected to 6.1 Courselets.

They would have to use LTI links to log in to their account again (can we add a button for this on Courselets?).

We can switch on/off this redirect.

**Comment by cjlee112** [comment]
@maxsocl What is the status / plan for this?  I have a vague memory that you already implemented something like this back in the original LTI project.  Does Courselets currently support anything like this?

**Comment by maxsocl** [comment]
@cjlee112 Yes, Courselets support this except redirect to new UI and enable/disable the redirect.

**Comment by alexbojko** [comment]
pushed to branch feature/issue#295
