### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#313]
This page lists all answers in a unit.

It contains:
* A list of answers. Each item contains:

   > Student name and avatar.
    A timestamp.
    An excerpt from the answer.
    A link to 8.2.1 Answer.

**Comment by alexbojko** [comment]
@maxsocl how can I get student's avatar? we have avatars only for instructor (am I right?)

**Comment by maxsocl** [comment]
@alexbojko Yes, we have only Instructor avatar now. So we can't get Student icon for now.

**Comment by DenisKolesnik** [comment]
Student icon cant be seen for now.
