### ISSUE TITLE
Instructor option to start a NEW chat?

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#320]
When an instructor is building a new courselet, typically they want to go through several rounds of viewing it in the student ChatUI and revising the courselet.  The current UI blocks them from doing that because once they start a Chat session of that courselet (typically via LTI link), they cannot start a NEW chat session for that courselet (it will always just show them the old Chat session).  The one workaround I've found is to manually delete the Chat object (via the admin interface).  

Is there a simple way to create a new Chat session, such that we could just give the Instructor a "Try it Out" button that would just put them in a brand-new Chat session to see exactly how the courselet will be shown to students?  Making it really easy for instructors to check how the courselet is going to work for students is crucial.

I'm also wondering whether the existing student UI gives students any way to do this.  I.e. can a student easily start a new chat session on a courselet they already did?

**Comment by maxsocl** [comment]
@cjlee112 

This was issued in https://github.com/cjlee112/socraticqs2/issues/259

Fixed in https://github.com/cjlee112/socraticqs2/pull/270

Currently in review.

**Comment by karluxd** [comment]
@cjlee112 We could definitely
