### ISSUE TITLE
[4] Instructor needs simple student response table for courselet (4)

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#323]
The vanilla instructor UI gives no easy way to see a table of student responses to a courselet.  This is needed for many basic functions such as checking the responses of a specific student.  For now, even a simple table view would be a huge improvement.  One of our instructors suggests:

* table whose rows are students, and whose columns are the ORCT questions in the courselet.
* first column would be student name
* each subsequent column would one question in the courselet (in their order in the courselet).
* if student has not answered the question, cell is blank.
* if student has answered, cell shows their selfeval and status on that question.  selfeval should be hyperlink to a page showing detailed information on that student response (text, confidence, timestamp, selfeval, status, errors)

**Comment by maxsocl** [comment]
@cjlee112 what about Students answered twice?

**Comment by maxsocl** [comment]
Done in https://github.com/cjlee112/socraticqs2/commit/5a297d47e7927ef187d7953c3fe056c2c84dee0a

**Comment by DenisKolesnik** [comment]
The bug has been verified on staging
