### ISSUE TITLE
[Gaston] Clear student data

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#339]
Instructors would like the option to clear all the data of each student for each lesson and for each courselet, e.g. after the student drop out or complete the course.

**Comment by cjlee112** [comment]
In general, we should not delete data as suggested here: the statistical validity of the dataset (e.g. for improving the effectiveness of the site and its methods) depends on having an unbiased and complete data sample.

**Comment by xqrongm** [comment]
Gaston would like to the option to clear student trails (not sure if "trails" means different things than "data" to you), because of the issues with the student Silvia/Ziling Huang as described in email thread "17W-LIFESCI23L-1: Cannot access Formative assessment". Is there other solution that I can tell Gaston about?

**Comment by maxsocl** [comment]
@cjlee112 @xqrongm We need a redo Courselet button as described in #259
