### ISSUE TITLE
[2] [Gaston] Enable opening a new window or tab when directed to outside webpage (2)

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#341]
In students' chat interface, when a student clicks the link to an outside website such as wikipedia, the current default action is to switch to the new webpage in the same window/tab. Students seem to prefer the default action to be opening a new window/tab for the outside page, so that they won't be navigated away from Courselets interface.

**Comment by DenisKolesnik** [comment]
@maxsocl 
A link is still opens in the same tab when clicking by the Read More link
![read_more](https://cloud.githubusercontent.com/assets/11578840/25170124/1bda3d2c-24f2-11e7-92bd-7730d7327b80.png)

**Comment by maxsocl** [comment]
All links outside a Message are opening in a new tab. Links for More information will be changes later - it is a technical difficulty with markdown text.

**Comment by xqrongm** [comment]
"Links for More information will be changes later - it is a technical difficulty with markdown text" continued in #439
