### ISSUE TITLE
[Gaston] Turn off auto-send by `Enter`

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#342]
In students' chat interface, when students type in their answers to a question, the content is sent upon a pressing the Enter key. Students would prefer Enter resulting in a line return in the text instead of sending, and that sending should only be triggered by clicking the "Send" button or a keyboard combination such as Ctrl + Enter.

**Comment by alexbojko** [comment]
link with issue #199

**Comment by alexbojko** [comment]
this issue is already fixed in branch fix/issue199
user send data to the server only by hitting Send button, not by Enter

**Comment by xqrongm** [comment]
It looks like even though `Enter` creates a line break when student is typing, it becomes a space after the message is sent. Instructors think it would be better for line break to stay as line break. Is it difficult to implement?

**Comment by redilonka** [comment]
@xqrongm Students can create formatted answer to include some equation. So we preformat text before render. This behavior is defined.

![screenshot_60](https://cloud.githubusercontent.com/assets/15940935/24054780/1c03d33c-0b46-11e7-9534-f466f8d8609c.png)

**Comment by xqrongm** [comment]
These formatting can be useful, but unfortunately most students don't have the patience to read the instruction and create formatted text accordingly. When they see line breaks become spaces, they'll just start complaining instead of doing extra formatting work to make sure line breaks stay line breaks.

**Comment by maxsocl** [comment]
@xqrongm ok, I will discuss this with Chris. Is it critical issue for us? If so - we can deploy changes as hot fix before Hedgehog release 30.03.17

**Comment by xqrongm** [comment]
Instructor hasn't indicated that this is very urgent. I believe it's more of an inconvenience than a problem. It can be fixed in the upcoming release instead of right now, unless instructors tell me otherwise in the future.

**Comment by maxsocl** [comment]
Decided to not disable formatting feature.
In a future something like wysiwyg editor or provide for description for Students.

**Comment by xqrongm** [comment]
For my own and instructors' reference, the format for chat content is Markdown, i.e. one line return in raw text is displayed as a space after sent, two line returns in raw text is displayed as one line return after sent
