### ISSUE TITLE
[12][8] [Gaston] Bring back the feature of assigning confidence to an answer (4)

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#343]
Students used to be able to assign confidence to their answers to questions in the old platform. This feature seems gone in the student's chat interface, it'll be nice to have it back in there.

**Comment by maxsocl** [comment]
Need to add `CONFIDENCE` and `GET_CONFIDENCE` FSM Nodes.

**Comment by DenisKolesnik** [comment]
#513

**Comment by DenisKolesnik** [comment]
#527 #526 #528

**Comment by DenisKolesnik** [comment]
Implemented

**Comment by xqrongm** [comment]
There is a type in "Type you confidence", where "you" should be "your". Also instructor suggested that "Please choose your confidence level." is more proper and polite.

**Comment by DenisKolesnik** [comment]
Implemented
