### ISSUE TITLE
[Gaston] System notification about student progress is sometimes confusing

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#344]
System notifications to inform student's progress sometimes don't convey the messages they are supposed to.

For example, after each question/lesson, if students choose "Different" or "Close", after they get through the help materials, a notification will show up "Congratulations! You have completed the core lessons for this courselet. See below for suggested next steps for what to study now in this courselet". This is misleading because there can be more questions/lessons for the same courselet afterwards, and a notification like this shouldn't show up until all the questions/lessons are completed. After each question/lesson, there can be a notification like "You have completed lesson 3 of 10".

In addition, after all the questions/lessons are completed, a notification shows up "Resources is there", but it doesn't give clear instructions. It can be changed to e.g. "Please look over the available resources in the side panel."

**Comment by maxsocl** [comment]
Done in https://github.com/cjlee112/socraticqs2/issues/373

**Comment by redilonka** [comment]
![screenshot_47](https://cloud.githubusercontent.com/assets/15940935/23858847/86c38940-080a-11e7-9263-eab9a60e67dd.png)

**Comment by maxsocl** [comment]
Fixed in b6ff72760d9fbf1bd5225ae8e65b5520e410eae4

**Comment by redilonka** [comment]
we need to process all notifications. I see much notifications which is confusing @xqrongm 
![screenshot_52](https://cloud.githubusercontent.com/assets/15940935/23965537/e9b4d25e-09c0-11e7-8997-cec3543c8aa5.png)

**Comment by redilonka** [comment]
>> After each question/lesson, there can be a notification like "You have completed lesson 3 of 10". 
need to discuss further
