### ISSUE TITLE
[Gaston] Pre-defined error models need improvement

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#345]
After a student gets a question wrong, several error model options show up, including the ones created by the instructors and those pre-defined in the system. Instructors cannot see the pre-defined ones when they were creating error models for the question, but the students can see those on the chat interface. After students choose those, the instructor then can see them in instructor's interface.

Dr. Gaston Pfluegl mentioned that in his "PCR courselet", the pre-defined error models include "I didn't know a basic definition needed for this question", "I got hung up on a detail and didn't think through the main question", "I misread the question", etc.. In his courselet, for different questions, each pre-defined error model is linked to the same content, which is not desired.

When I tested this out in my "Xiaoqing example course", the pre-defined error model was "error_concept" and there can be multiple of them. And when students choose "error_concept", no resource shows up for them. This "error_concept" is not desired either.

Instructors would like to be able to access these pre-defined error models before students can, and activate/deactivate, hide/show and/or edit them. In addition, some complain that each error model takes too much space on the students' chat interface.

**Comment by maxsocl** [comment]
@cjlee112 Need to discuss

**Comment by redilonka** [comment]
@cjlee112 should we allow Instructors to edit predefined EM's?
@xqrongm I propose to add SHOW/HIDE feature for Instructors.

**Comment by xqrongm** [comment]
@redilonka SHOW/HIDE feature sounds good.

**Comment by xqrongm** [comment]
A follow-up from Gaston's reply to Chris' email "server error on new Courselets release":

> Can we also limit the presented error-models as discussed today.
>  
> For example in the list below I only designed the top two myself and I would like not to present the other 6 models.
> 
> ![image](https://cloud.githubusercontent.com/assets/12205732/25595973/ea52c9ac-2e94-11e7-8656-ac42231afbd4.png)
>

**Comment by cjlee112** [comment]
we already fixed this in a previous maintenance release, so why are the generic EM back in the Apr. 27 release?

**Comment by xqrongm** [comment]
from my initial comment on this issue: "for different questions, each pre-defined error model is linked to the same content, which is not desired."

Can this be easily fixed? i.e. allowing error models with the same text to be linked to different resources for different questions, i.e. "I don't know" of question_1 linked to resource_1, "I don't know" of question_2 linked to resource_2, instead of both linked to resource_1.
