### ISSUE TITLE
[Gaston] Un-publish/hide or delete a courselet after it's published

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#346]
After a courselet has been published, instructors would like the option to un-publish/hide the courselet (i.e. students can no longer access it but the instructor still can) and re-publish it, as well as the option to delete the courselet (wipe it out so it no longer exist in the Courselets system).

**Comment by maxsocl** [comment]
@cjlee112 
What do we want to do on Un-publish actions?
Do we want to remove releasedTime for Courselet completely or save history of publish/unpublish actions somewhere?

**Comment by maxsocl** [comment]
Done in df4291fd7ba97e18e2c682442f8cd7fc42ed51f9

**Comment by redilonka** [comment]
@maxsocl 
steps:
1) open "edit courselet"
2) click to publish button
AR: courselet title delete/hide in input
ER: courselet title stays on the place 
![screenshot_50](https://cloud.githubusercontent.com/assets/15940935/23904455/932a7682-08d0-11e7-833d-56578534525f.png)

**Comment by maxsocl** [comment]
Fixed in b6ff72760d9fbf1bd5225ae8e65b5520e410eae4
