### ISSUE TITLE
pypandoc dying on wikipedia content

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#35]
observed this on the production server, e.g. Bayes' theorem

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367466394268)

**Comment by cjlee112** [comment]
This appears to be a unicode issue.  Deleting the second half of the text (containing non-ASCII characters) eliminates the crash.  Note that I wasn't able to reproduce this crash on my development platform.

**Comment by maxsocl** [comment]
I can't reproduce this bug too.
