### ISSUE TITLE
[4] LTI: grade return is not implemented. we need to return 0..1 based on the amount of questions completed (4)

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#350]
1. Investigate LTI grading feature.
2. Implement grading method.
2. Use grading based on Courselets (ChatUI) ORCT answered.

**Comment by maxsocl** [comment]
@cjlee112 

1. Do we want return grade on each answer? 
2. What do we need to do if Courselets will be restared?

**Comment by maxsocl** [comment]
![img_20170310_010052](https://cloud.githubusercontent.com/assets/877401/23774622/2be54f2a-052d-11e7-9a51-3316deea94aa.jpg)

**Comment by redilonka** [comment]
![screenshot_66](https://cloud.githubusercontent.com/assets/15940935/24503018/ed1ba6fe-1558-11e7-95ec-1d00b33fde42.png)
![screenshot_67](https://cloud.githubusercontent.com/assets/15940935/24503019/ed1ca842-1558-11e7-810f-9f4cf3444cfd.png)
<img width="692" alt="screen shot 2017-03-30 at 2 55 23 pm" src="https://cloud.githubusercontent.com/assets/15940935/24503048/1b7cec6a-1559-11e7-8308-2cda8a60eca6.png">
