### ISSUE TITLE
[Gaston] instructor wants to see from a specific student's view

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#354]
This request was motivated by the existence of multiple aborted student trails on Gaston's courselets. For example, in his "PCR Courselet", these student trails are aborted - 73, 143, 254, 284, 371, 389, 398, 493, 496, 514; in his "Lab F Gel Electrophoresis" - these student trails are aborted - 93, 149, 150, 237, 291, 444, 465, 522, 526.

Gaston is wondering (1) if students just stopped working on it, or (2) if the system stopped working for them. He wants to follow up on that with the students. Before he does that, he would like to know what each of those students is seeing in their Courselets interface, so he would like a feature where he can "set his role" to a specific student and be able to check in on the student's progress.

For students' privacy, instructor A should only be able to see students' views on in instructor A's courselets, instructor B will only be able to see students' views on in instructor B's courselets, etc..

**Comment by xqrongm** [comment]
The need for instructor to see from each student's view has come up several times now, so I'd like this issue be high-priority. Thanks!

**Comment by DenisKolesnik** [comment]
How to use "See from a specific student's view" feature works:
1. Go to admin, open your user and take a look at the groups
2. Add “Can_login_as_other_user” group to chosen groups column and save.
3. Open any user page in which you want to login and click “Login as user” button

Important info:
You will be logged in to student account and all actions which you perform - can change student progress.

**Comment by DenisKolesnik** [comment]
Feature Implemented

**Comment by xqrongm** [comment]
Thanks everyone for implementing this! It's great for troubleshooting by admin users.

Is it difficult to implement any of the following?
1. A read-only option for this feature, i.e. when User A logs in as User B, User A cannot change anything in User B's account
2. Differentiate the actions performed by the User A logging in as User B vs. User B logging in as User B
3. Enable User A to perform actions on User B's account for testing and then reverse the actions when User A logs off as User B
