### ISSUE TITLE
[Gaston] instructor wants to access students' database to analyze usage

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#355]
Gaston mentioned that he has been requesting student data (currently not accessible through instructor's interface) to analyze students' usage and performance on his courselets, in order to understand students' needs and improve his courselets. Examples of such data include (1) how much time does each student spend on each lesson, (2) which specific error model was selected by which specific student(s) for each question, etc.

It would be nice to make such data accessible through instructor's interface. It is understood that a lot of discussion is needed regarding how to implement this feature.

**Comment by maxsocl** [comment]
@xqrongm First step to implement this feature is issue #125

**Comment by xqrongm** [comment]
Gaston recently needs data dump to establish which student participated to assign participation scores, and his request was time-sensitive because the school imposed a deadline for submitting grades. I'm wondering if such requests would put this issue higher on the priority list.
