### ISSUE TITLE
[2] Update to Facebook v.2.3 ()

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#356]
Need to update facebook API to v.2.3.
2 year lifetime ends on 27 of March.

**Comment by maxsocl** [comment]
Staging APP is already on the latest version of the API. So we can move Production App iteratively from 2.2 to 2.3 Graph version.

**Comment by redilonka** [comment]
![screenshot_46](https://cloud.githubusercontent.com/assets/15940935/23792533/062d1c78-0590-11e7-95c5-67369fe61542.png)

**Comment by maxsocl** [comment]
@redilonka 

App updated.
But now we have version conflict.
Facebook app has v2.8 but currently installed `python-socil-auth` uses v2.7.
As a result we have Auth Exception:

<img width="1156" alt="screen shot 2017-03-10 at 1 30 42 pm" src="https://cloud.githubusercontent.com/assets/877401/23793821/d042ef24-0595-11e7-8bd6-30c6fa26e581.png">


I am going to move issue to in progress to fix this.

**Comment by cmltaWt0** [comment]
Done
