### ISSUE TITLE
Update landing page links

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#358]
The courselets.org landing page directs the visitor to just a few main links:

* /ct/courses/: the old UI's "Public Courses" list.  We no longer want to show either the old UI, or most of these "courses" (which are either incomplete or not ready for public consumption).

* "Learn More" links to an old Vimeo video.  We should update to something more current.

* "Take a look" and "View courses" both link to old UI "slideshow" of "Thinking Conditionally" courselet.  At a minimum, we should stop showing the old UI, and switch to new ChatUI.

**Comment by maxsocl** [comment]
@cjlee112 

1. So to clarify -  we need to hide `Public courses` link as top level link? And what do we need to do with `Enrolled Courses` link?
2. Switching to ChatUI for `slideshow` FSM will take some time.

**Comment by rimikt** [comment]
@cjlee112 please update this task - some points are not actual.
