### ISSUE TITLE
[2] Switch all links to ChatUI (2)

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#359]
Most of the top level pages on the site still link to the old UI.  We need to switch all of that to ChatUI, because that's what we want to show people from now on.

**Comment by maxsocl** [comment]
@cjlee112 
We need to list all links here.

**Comment by maxsocl** [comment]
@DenisKolesnik let's find all such links.

**Comment by maxsocl** [comment]
Can't find more links to change. Task will be closed.
@cjlee112 can you give us some particular links to change?
