### ISSUE TITLE
Update Landing Page text

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#360]
We basically need a whole new landing page design.  As a quick starting point we could adapt what Karl designed for the conceptinventory.org landing page, with a somewhat different text.

**Comment by maxsocl** [comment]
@cjlee112 

conceptinventory.org landing page almost done as Django CMS template with all placeholders.

I will create a task for this in Current Support Project.

**Comment by rimikt** [comment]
Fixed
