### ISSUE TITLE
[need research] I can't log in system through oauth-oauth

### ISSUE THREAD

**Issue by redilonka** [cjlee112/socraticqs2#362]
precondition: 
- you should have khan academy account registered with facebook auth
- you should be logged out in khan academy

steps:
1) open the system 
2) click in "sign up"
3) choose "knah academy"
4) redirect to login in knah academy
5) choose "fb oauth"

AR: error
![screenshot_31](https://cloud.githubusercontent.com/assets/15940935/23550393/3ddad89e-0019-11e7-8e3b-cfcac9049f3d.png)
ER: I should login in our system

**Comment by cmltaWt0** [comment]
Not relevant
