### ISSUE TITLE
ChatUI start doesn't list concepts properly

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#364]
I created a courselet containing both a definition and an ORCT question about a specific concept.  However, when I went to the ChatUI for that courselet, "What you will learn about" was displayed as empty (no concept listed).  Interestingly, when I moved the definition from being a core lesson to just being a Resource, then the ChatUI displayed that concept as "What you will learn".

This should be fixed as follows:

* "What you will learn about" should list concepts that are TESTED by lessons in the core lesson sequence for this courselet.

**Comment by maxsocl** [comment]
@redilonka Test it please on stage
