### ISSUE TITLE
[2] ChatUI doesn't show links to More Information (2)

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#365]
I added a lesson that links to a Wikipedia page via its URL attribute.  In the old UI, students would see this as a clickable link to "more information here".  But the ChatUI shows the student no clickable link whatsoever for the lesson's URL attribute.   It should. (per #341, clicking the link should open in a separate tab / window).

**Comment by maxsocl** [comment]
Added `Read more` link in Lesson messages.

Still opened in the same window due to pandoc - need to hack somehow.

**Comment by DenisKolesnik** [comment]
Links appears. The bug has been fixed
