### ISSUE TITLE
[2] ChatUI doesn't show lesson author name (2)

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#366]
Currently, ChatUI shows all lesson content as coming from the instructor, even if Lesson.author is someone else.  In the latter case, ChatUI needs to display the Author name, just like the old ui did.  Maybe show it next to the lesson title, and linked to the author's profile page?

**Comment by maxsocl** [comment]
Since we have no any normal Instructor profile page Author will be simple bolded text w/o any link to profile page.
Later we need to add this link.

**Comment by DenisKolesnik** [comment]
The name of an author has been added
