### ISSUE TITLE
[1] [Gaston] The links on the home page of a courselet under "YOU WILL LEARN ABOUT" point to the old interface (1)

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#381]
For example "PCR Primer Annealing" point to the page on the old platform (https://www.courselets.org/ct/courses/18/units/115/concepts/5030) instead of the new chat interface as it's supposed to. 

It is high priority because it's very confusing to students. Instructors are also concerned that students may start working from the old platform and their progress can't be displayed properly on the new platform. If this is the case, please investigate whether this has happen to any student and how to resolve this problem. Thanks.

![image](https://cloud.githubusercontent.com/assets/12205732/24024744/16aefaf2-0a8c-11e7-8bdc-6013b2fac436.png)

**Comment by maxsocl** [comment]
@xqrongm 
Section `will learn` and `need to know` contains a list of `Concepts` and we have no NEW UI to display single Concept.

Also each Concept can has `url` to Wikipedia page related to this Concept. So as a solution - Instructor **should** add Wiki link as Concept url.

I will check that current implementation tries to check all possible items to find Wiki url.

**Comment by xqrongm** [comment]
Instructors still feel that displaying a list of `Concepts` linked to Wikipedia pages is confusing. It kind of puts too much emphasis on external resources instead of the main contents of each cousrelet. Currently instructors are using  `Resources`, which cannot be accessed by students before the courselet is completed. They show up on the left sidebar bottom as 'Resources'. Instructors think it not necessary to show the same resource in the entry page.

**Comment by xqrongm** [comment]
"Also each Concept can has url to Wikipedia page related to this Concept. So as a solution - Instructor should add Wiki link as Concept url."

Instructor has tried to add URL to existing concepts, but because of the issue described in #383, they are not able to add it through the "Url" field, and adding URL in "Text" field doesn't work.

**Comment by xqrongm** [comment]
Instructor suggested that the link should be displayed only on the front page if a URL is given in the lesson, otherwise it should not be shown. This way instructor would be able to control what is displayed on the front page.

**Comment by xqrongm** [comment]
It may be helpful to explain on the instructor's interface: what contents will be shown as links under `will learn` and `need to know`.

**Comment by maxsocl** [comment]
Steps to check:

- add URL to Lesson described Concept
- Refresh LMS page

**Comment by DenisKolesnik** [comment]
An URL in the lesson which describes a concept, opens correctly

**Comment by xqrongm** [comment]
The design of "YOU WILL LEARN ABOUT" is discussed here: #364
