### ISSUE TITLE
[2] Can we have a section or weblink on Courselets platform for FAQ (1)

### ISSUE THREAD

**Issue by redilonka** [cjlee112/socraticqs2#382]
(currently in here https://drive.google.com/file/d/0B6niC-ArLzlFa2FfUzVzUllmYlU/view?usp=sharing). The final format of FAQ section doesn't have to be a .xlsx doc.

**Comment by maxsocl** [comment]
@xqrongm @cjlee112 @redilonka 

We need to create CMS page `FAQ` to be editable by content manager.
So need to decide where this page should be placed.

**Comment by maxsocl** [comment]
So I can start from simple page implementation and it will be included in next release https://github.com/cjlee112/socraticqs2/milestone/5

**Comment by maxsocl** [comment]
Need to add new CMS page with template FAQ Page
