### ISSUE TITLE
[Gaston] "Url" field missing for editing existing concept

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#383]
There is a "Url" field in the page to create a new concept/resource, but it can no longer be found when editing this concept/resource. For lessons under a courselet, the "Url" field is available for some lessons but not for others.

Creating a new concept, with "Url" field
![image](https://cloud.githubusercontent.com/assets/12205732/24059216/8d45150a-0b24-11e7-999f-f4dcd348a404.png)

Editing an existing concept, without "Url" field
![image](https://cloud.githubusercontent.com/assets/12205732/24059243/bc754bba-0b24-11e7-9ddb-c86c00d91f81.png)

**Comment by maxsocl** [comment]
Wrong flow.
Concept item has no URL field.
On screenshot 1 we can see `Lesson` object with URL field.
Lessons can define Concept somehow and Lesson can has URL.

**Comment by xqrongm** [comment]
Just for my own and instructors' reference, whether an item is a concept (has URL field for editing) or a lesson (doesn't) is not determined by whether it shows up in the "Lessons" tab, instead it is reflected in its own URL.

The two items below both show up in the "Lessons" tab, however, one has URL field for editing while the other doesn't.

This is a lesson with URL field for editing:
https://www.courselets.org/ct/teach/courses/21/units/107/**lessons**/5565/

This is a concept without URL field for editing:
https://www.courselets.org/ct/teach/courses/21/units/107/**concepts**/4849/
