### ISSUE TITLE
[BUG] Can't add ORCT Unit

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#388]
Trying to add ORCT by no area for Answer in appeared

<img width="786" alt="screen shot 2017-03-22 at 8 17 44 am" src="https://cloud.githubusercontent.com/assets/877401/24184725/0c5e2c9e-0ed8-11e7-89a3-991b3a70cbb5.png">

**Comment by alexbojko** [comment]
fixed and pushed to branch fix/issue#388
