### ISSUE TITLE
[BUG] Can't start to create Unit by a Chat using sidebar button

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#389]
<img width="549" alt="screenshot at mar 22 08-27-54" src="https://cloud.githubusercontent.com/assets/877401/24185007/7d13afc6-0ed9-11e7-98c8-0a5ff7ffe9d2.png">

**Comment by alexbojko** [comment]
added link to this button, so now clicking on this link chat window will be opened
pushed to branch fix/issue#389

**Comment by alexbojko** [comment]
fixed and pushed to branch fix/issue#389
