### ISSUE TITLE
The "RelatedObjectDoesNotExist at /accounts/" error message appears when user opens "accounts" page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#390]
STR:
1. Login to the system and open https://dev.courselets.org/accounts/ page
2. Take a look at the error

![error_account](https://cloud.githubusercontent.com/assets/11578840/24196809/d2051fdc-0f07-11e7-8e4e-c439972ffbab.png)

**Comment by alexbojko** [comment]
I suppose that only instructors can log in using email, so when user logs in using email I will create Instructor object for him, if not exist yet.

**Comment by alexbojko** [comment]
fixed and pushed to branch fix/issue#390
