### ISSUE TITLE
The rules for password field are missed

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#391]
STR:
1. Open the SignUp page and create new account using any input in the password field. (For example use space as input)

Actual result:
Form accepts any input in the password field

Expected result:
The password field has validation for input and it's possible to create new user using space as password

**Comment by alexbojko** [comment]
could you pls clarify what rules exactly should I use for this field? min\max chars, special symbols?

**Comment by DenisKolesnik** [comment]
@alexbojko 
Validation rules:
1. At least 6 characters long (including 6)
2. At least one capital letter
3. At least one number

**Comment by alexbojko** [comment]
added pwd validator - 1 capital char, 1 digit, min 6 chars.
fixed and pushed to branch fix/issue#391
