### ISSUE TITLE
The "forgot pass" and "singup" links are missed on the login page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#392]
![login_page](https://cloud.githubusercontent.com/assets/11578840/24204503/6569a9aa-0f21-11e7-830f-81809ed39a2e.png)
STR:
1. Open the login page https://dev.courselets.org/new_login/

Actual result:
There aren't "forgot pass" and "singup" links on the login page

**Comment by alexbojko** [comment]
fixed and pushed to branch fix/issue#392
