### ISSUE TITLE
The "TypeError at /chat/preview/enrollcode/4ec7b5a9f1723630611f/" error appears when trying to preview a courselet

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#405]
STR:
1. Preview the course
2. Take a look at the error message
![error](https://cloud.githubusercontent.com/assets/11578840/24302826/a1d28ece-10bc-11e7-8d71-570e911d2a66.png)

**Comment by alexbojko** [comment]
duplicates issue #387 and already in PR- #398

**Comment by DenisKolesnik** [comment]
The bug has been fixed
