### ISSUE TITLE
User cant open shared course when he don't have own courses

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#408]
STR:
1. Share course with a user who dont have own courses
2. Open courses page from user whom you just shared a course

Expected result:
User have links to shared courses

Actual result:
User don't have link to shared course on the "shared courses" page
![111](https://cloud.githubusercontent.com/assets/11578840/24352120/fabe6f5e-12f0-11e7-8541-7ec95b371dd9.png)

**Comment by alexbojko** [comment]
this ticket will be fixed once we merge new Invites system. I checked it out and it's fixed there.
