### ISSUE TITLE
Linked concept links again after reloading the page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#415]
#377 
str: (ct/teach/courses/4/units/16/concepts/231/errors/)

1.open courses
2.open units
3.open concepts
4.open errors
5.search for concept
6.Link concept and reload the page
7. Take a look at that there are more than one concept has attached

ER: Selected concept is linked
AR:  The same concept is linked every time when user reload the page
![23](https://cloud.githubusercontent.com/assets/11578840/24493408/5ed0b22a-1537-11e7-9864-2f8c3a913aab.png)

ISSUE ALSO PRESENTS ON  PRODUCTION
https://courselets.org/ct/teach/courses/7/units/49/concepts/1541/errors/

**Comment by maxsocl** [comment]
We do not need to fix OLD UI bugs.
