### ISSUE TITLE
[Gaston] instructor's access to students' JSON data

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#416]
Add a section in instructor's interface to access students' JSON data at https://www.courselets.org/api/v0/courses/21/responses/ ("21" can be replaced by any courselet number).

Also enable downloading this data in tabular format.

as part of #355

**Comment by xqrongm** [comment]
If possible, please make sure the error "502 Bad Gateway" for course 18 is fixed in the upcoming release, thanks.

**Comment by DenisKolesnik** [comment]
The feature works
