### ISSUE TITLE
[Sharing]The error appears when open the student invitation

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#427]
STR:
1. Send invitation to a student
2. Open it and take a look at the error

![error](https://cloud.githubusercontent.com/assets/11578840/25182737/462c9eea-251e-11e7-8347-373134b12fe3.png)

**Comment by alexbojko** [comment]
this bug is already fixed. 
In case if this bug is still reproducible - delete all EnrollUnitCodes. This will fix it.
