### ISSUE TITLE
[Sharing]Tester can get access to a course, adding /ctms/course/5/courselet/ to a course

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#428]
STR:
1. Send invitation to a tester
2. login to tester account, accept invitation and open Courselet of shared course 

ER: The 404 error appears cause tester dont have access to courselet page

AR: Tester has access to courselet page and can edit it

**Comment by sendr** [comment]
cannot reproduce, I think it's already fixed
