### ISSUE TITLE
[Sharing]It's possible to send invitation when already assigned as a tester/student to a course

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#429]
STR:
1. Send invitation to a tester
2. Accept it from tester's side
3. Send invitation again

ER: It's impossible to send invitation to a user who already assigned as a student/tester to a course
AR: It's possible to send invitation when user already assigned as a student/tester to a course

**Comment by alexbojko** [comment]
this functionality was included in app design - it will resend email to user, it duplicates functionality of button "Send new Invite"

@maxsocl, do you think - should I remove this function?
