### ISSUE TITLE
The error message appears when user click the "Course" button

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#430]
Additional Info:
1. The issue appears in student LMS
2. The issue appears in Instructor Preview
![course_button](https://cloud.githubusercontent.com/assets/11578840/25223709/d08a401e-25c4-11e7-8f65-f6828d283222.png)
![error](https://cloud.githubusercontent.com/assets/11578840/25223711/d08ce9ae-25c4-11e7-9eb3-1563be3dca03.png)

**Comment by sendr** [comment]
fixed
