### ISSUE TITLE
Only error title appear in the Chat UI

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#432]
STR:
1. Add error model filling title and text fields
2. Save it and open in the course preview or as an enrolled student

ER: Student sees title and text of the error model

AR: Student sees only title

**Comment by cjlee112** [comment]
@DenisKolesnik It sounds like you mean Step 1 is to be done in the new Instructor MVP UI, but you didn't specify at all how Step 1 is to be done.  This AR is not reproducible when Step 1 is done in the older (original) Instructor UI.
