### ISSUE TITLE
Error model is repeated in the Chat UI after editing it

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#433]
STR:
1. Add an error model to a course
2. Open it in the preview course or as enrolled student and take a look at the created error model
3. Edit the error model (change title or text) and save it
4. Open it in the preview course or as enrolled student again and take a look at the amount of error

ER: Amount of errors in the Chat UI is the same as amount of errors in the unit

AR: Amount of errors in the Chat UI is bigger than amount of errors in the 
![2](https://cloud.githubusercontent.com/assets/11578840/25234453/c42da33a-25ea-11e7-8724-fd017c037141.png)
![1](https://cloud.githubusercontent.com/assets/11578840/25234454/c42e7210-25ea-11e7-9597-429781af6c5e.png)

unit

**Comment by alexbojko** [comment]
@DenisKolesnik, could you pls check error models count in Unit edit form? will it be change after editing error models?

**Comment by DenisKolesnik** [comment]
@alexbojko The amount of units on the edit page isn't changed

**Comment by alexbojko** [comment]
yes, it's reproducible. 
in admin:
<img width="1278" alt="screenshot at apr 20 18-07-05" src="https://cloud.githubusercontent.com/assets/370714/25237786/5015754a-25f4-11e7-97e5-5751d1d6c3f3.png">

**Comment by sendr** [comment]
It seems to be fixed, cannot reproduce it.
