### ISSUE TITLE
The "delete account" feature on the profile page doesn't delete account

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#435]
STR:
1. Click the delete account button
2. Confirm deletion and take a look at the reaction

ER: The account is deleted and user log out user from the system automatically
AR: the account isn't deleted.

**Comment by alexbojko** [comment]
fixed in scope of ticket #428

**Comment by sendr** [comment]
After deleting cannot login
![screen shot 2018-10-18 at 3 59 35 pm](https://user-images.githubusercontent.com/1757048/47156040-dc027c80-d2ee-11e8-843f-21853ee94fe1.png)
and sign up
![screen shot 2018-10-18 at 4 00 53 pm](https://user-images.githubusercontent.com/1757048/47156113-0fdda200-d2ef-11e8-9f45-16ae3e9f1e14.png)

**Comment by cmltaWt0** [comment]
@karluxd let's discuss about deleting use case
