### ISSUE TITLE
Lesson authorship in ChatUI needs refinement

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#443]
The new display of the author's name in each lesson needs improvement:

- it is totally redundant to display such a message when the author = the instructor.
- the current format is incompatible with Chat.  Nobody in a chat starts a message by typing "Author: me".  
- To me the Author info seems like it belongs with the lesson title, i.e. at the heading of the lesson section.

We need input from @karluxd on this.

**Comment by karluxd** [comment]
@cjlee112 @maxsocl How common is it to have different authors within the same courselet? Is it not enough to show this information in the introduction with the prerequisites etc?

**Comment by karluxd** [comment]
Maybe we can just remove the author info from the chat and close this? We currently show the author name below the courselet name (at least on the dev server). If so, do you need any help with this @maxsocl?

**Comment by cjlee112** [comment]
@karluxd So yes, in answer to your question, just showing the instructor's name in the prereq intro is enough authorship info for now.  In the future when instructors are often re-using each other's lessons I recommend that author != instructor name be shown with the lesson title, not in the Chat message.

**Comment by cjlee112** [comment]
@karluxd I agree, we can just remove the author info from the chat now to close this.

**Comment by DenisKolesnik** [comment]
#471
