### ISSUE TITLE
[Gaston] "Something went wrong" and “Server Error (500)”

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#444]
This is based on Gaston's email "trouble with courselet" and Chris' email "server error on new Courselets release", copied at the end. Gaston wants this to be fixed as soon as possible.

I got “Server Error (500)” at "https://www.courselets.org/lms/courses/26/"

Then I went to "https://www.courselets.org/lms/courses/19/" and start working on the courselet as an enrolled student at "https://www.courselets.org/chat/enrollcode/9858122ee8d046a8a89af92839432413/", like Gaston said, at about lesson 10, I got “Something went wrong. Please refresh the page and try again a little later”

Below is Gaston's email:

> Hello,
>  
> I am working on launching my next courselet this Tuesday for LS23L.
>  
> https://www.courselets.org/ct/teach/courses/26/units/138/
>  
> This is in Course
> “UCLA LS23L Life Sciences Core Laboratories S17”
>  
> After completing the draft and publishing I am getting two errors:
>  
> Error 1. In the middle of doing the courselet
> “Something went wrong. Please refresh the page and try again a little later”
>  
> And
>  
> “Server Error (500)”, trying to run this courselet as an Enrolled  Student from  https://www.courselets.org/ct/
>  
>  
> I copied all 13 lessons of course 26 unit 138,  into https://www.courselets.org/ct/teach/courses/19/units/143/
> This is in Course
> “UCLA LS23L Life Sciences Core Laboratories S17”
>  
> I tried to get through it by not using the error models, (responding with 'essentially the same' and avoiding error models)
>  
> I got to Lesson 10 then it stopped working (“Something went wrong…”). not sure if it’s me or the system.
>  
> Can this be fixed before Tuesday?
>  
> GMP

Below is Chris' email:

> Hi Maksim, Sergiy,
> we seem to have a server error in the latest release (from Thursday), that blocks the student from completing a Courselet (after the first question, in the test I just ran to reproduce what Gaston reported, but I'm not sure what triggers it or when).  Here are the steps I took to reproduce this:
> 
> * loaded this Courselet URL (I tested in Firefox 51)
> 
> https://www.courselets.org/chat/enrollcode/9858122ee8d046a8a89af92839432413/
> 
> * started the courselet
> 
> * entered "testing 123" as my answer to the first question
> 
> * clicked "Different" as my self-assessment
> 
> * selected the first error model in the list
> 
> * clicked "Continue" when prompted
> 
> * Got a floating error message saying "Something went wrong. Please refresh the page and try again a little later"
> 
> Even after I deleted my chat session, returning to this URL gives me this error message now as soon as I try to begin the courselet.
> 
> I also heard from a student in my C100 class that they encountered the same error message on Thursday, so apparently the problem is not specific to Gaston's courselet.
> 
> -- Chris

**Comment by maxsocl** [comment]
@xqrongm can I close this issue?

**Comment by xqrongm** [comment]
A student named Nancy Hernandez encounters the same error message and could not proceed: "Something went wrong. Please refresh the page and try again a little later". Can someone check the status of her chat and see if anything needs to be fixed? Thanks

**Comment by xqrongm** [comment]
Another student Hwang Spring is reporting the same problem

**Comment by cmltaWt0** [comment]
Stale issue
