### ISSUE TITLE
[Gaston] time-out at https://www.courselets.org/api/v0/courses/18/responses/

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#446]
This is about Gaston's courselet. I don't remember the exact number, it may be 18 as in title or something else, the request resulted in error because the response is too large so the server timed out. Instructors can have large sizes of class (hundreds of students) and may need to request such large sizes of data routinely. Is it possible for the server to return such large response normally instead of time out?

**Comment by maxsocl** [comment]
@xqrongm this is done in #416 
see https://github.com/cjlee112/socraticqs2/issues/416#issuecomment-293813410

**Comment by xqrongm** [comment]
Sorry, the instructor brought up the time-out problem again, I just took his word for it because I can't access his content to test. So by using the "Download" button, the instructor won't have time-out problem no matter how large the data is? Would there still be time-out problem if using the direct link such as https://www.courselets.org/api/v0/courses/18/responses/ ?
