### ISSUE TITLE
The "wait for instructor..." message is duplicated when student waits for instructor action in Live Session Chat

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#447]
STR:
1. Open the ChatUI as a student and answer on a question
2. Take a look at the "wait for instructor..." message after answering

![chat_ui](https://cloud.githubusercontent.com/assets/11578840/25697973/bd3395e0-30c5-11e7-9ae6-b1bc0529e91d.png)

**Comment by maxsocl** [comment]
@DenisKolesnik another approach will be implemented - we are going to add Django Channels to use push notifications for this case.

**Comment by cmltaWt0** [comment]
Will be fixed using django channels or websockets
