### ISSUE TITLE
Display or hide author information for each lesson

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#448]
Instructor feels that the author information for each lesson is redundant when all the lessons are authored by the instructor him- or herself. But it is understood that the author information is necessary when one instructor utilize other instructors' content. I think we should discuss whether to allow instructors to choose between displaying or hiding the author information. If we do allow, we should enable operating on an individual lesson and on all the lessons at once.

**Comment by cjlee112** [comment]
This duplicates #443
