### ISSUE TITLE
[Gaston] student got stuck

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#449]
Here is the message from Gaston's student:

> I am trying to proceed in the courselet, but the same information pops up every time I press any of the three buttons below. I am stuck on chapter 11 and cannot finish the courselet.
> My UID is 204625955.
> 
> Soo Bin Lee
> soobinlee97@gmail.com

I think the student is stuck on this screen, and could not proceed by choosing any of the three options.

![image](https://cloud.githubusercontent.com/assets/12205732/25873466/a43d07e0-34dc-11e7-8fee-47ac75ed4b48.png)

**Comment by xqrongm** [comment]
The student is OK with deleting this chat and restart. I haven't deleted it yet because I'm not sure if the chat data is needed for troubleshooting. After this issue is resolved, if the student can't start where it was left off,  please delete the chat so he/she can start over. Thanks.

**Comment by maxsocl** [comment]
@xqrongm I've reassigned this chat to me to figure out the problem so Student can redo Courselet.
