### ISSUE TITLE
(#268)The progress bar in the Courselet History doesn't show correct progress

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#450]
STR:
1. Complete the courselet and take a look at the Courselet History

ER: The progress bar shows correct progress
![progress bar](https://cloud.githubusercontent.com/assets/11578840/25936867/1a19eb26-3632-11e7-826c-bf1cb65890bb.png)

**Comment by xqrongm** [comment]
Instructor Gaston said students are complaining about this, so we hope this can be resolved soon. Thanks!

**Comment by maxsocl** [comment]
@xqrongm already resolved and will be included in next week release
