### ISSUE TITLE
[Gaston] Multiple students with the same name

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#455]
Email from Gaston:

> Hi Everyone,
>  
> So I have two students with the name Joshua Kim this quarter and only one gets to do the courselet (please see below).
>  
>  
> Joshua Kim UID 204-578-138
>  
> And
>  
> Joshua Kim Woo 004-612-807
>  
> Only one Joshua has a record in Courselet 145:
>  
> Courseletid 145
> UnitLesson_id 6252
> Lti_identity 88921
> Author_id 1540
> JOSHUA KIM
>  
>  
> Seems like your database creates participants by name only not by UID.
>  
> I have often student’s with the same name not a rare occasion by 600 + students.
>  
> What can be done for this student?
>  
> Thanks
> 
> GMP

**Comment by maxsocl** [comment]
@xqrongm there is only one Student encountered this issue.
I will provide a solution to create separate account each account and fix this issue for future students.
But I need to know who is main person for this account - there are tree different LTI accounts from UCLA.

**Comment by xqrongm** [comment]
@maxsocl Please let me know once this is resolved, so I can get back to the students. Thanks.

Joshua Kim joshuawkim108@ucla.edu said on 5/13:

> PCR Courselet Spring 2017: I have completed all the Lessons and all the Resources. 
> Gel Courselet Spring 2017: I have completed all the Lessons and all the Resources.

Joshua Kim joshua5629@yahoo.com said today 5/17:

> I have completed the courselet for the GEL topic Lab F. However, this history tab doesn't say completed May 16 (today) but has my answers. Regardless, I have finished the courselet. My name is Joshua Kim, ID# 204578138.

> PCR Courselet Spring 2017: I have completed all Lessons and Resources 
> Gel Courselet Spring 2017: I have completed all the Lessons and Resources
> Completed on May 16, 2017.

> for the GEL courselet I was able to work on it from the beginning. 
> I will attach the screenshots for the "history tab". The screenshot that shows the history indicates May 13th which is not the date I completed it (I did it on May 16). When I click that one, my answers for the courselet that I completed on May 16 show up. I added a screenshot of what it looks like when I click the May 13 GEL courselet below as well. Those are my answers. 
> My answers are saved but the dates are projected incorrectly and as for the previous Courselet (PCR), that was the one that was already completed when I logged on.

![image](https://cloud.githubusercontent.com/assets/12205732/26175508/e41f31ea-3b20-11e7-8fa6-816dc5100b37.png)
