### ISSUE TITLE
custom_login ignores Django next URL, breaking login_required decorator pattern

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#46]
@maxsocl I saw this in testing a login_required view when not logged in.  It brought up the login form, but when I logged in, it redirected me to the /ct/ "Your courses" page rather than the original login_required view that the user is trying to view.  This is because psa.views.custom_login is hardwired to redirect to /ct/ rather than request.POST('next').  This seems important to fix as part of starting to show the site to (new) users.

**Comment by cjlee112** [comment]
@maxsocl Looks like there is also something wrong with how the next URL is getting passed through the custom_login view/form GET followed by POST.  I fixed the redirect in psa.views.custom_login() to use the next URL if provided by the POST, but it's not getting anything from the form.  Can you debug this please?

**Comment by maxsocl** [comment]
@cjlee112 
You are right.
There is a patch to apply below. It provide a `next` variable on GET request.

    diff --git a/mysite/psa/views.py b/mysite/psa/views.py
    index 37d49d5..727a953 100644
    --- a/mysite/psa/views.py 
    +++ b/mysite/psa/views.py 
    @@ -69,6 +69,7 @@ def custom_login(request):
                                                                   {
                                                                       'available_backends': load_backends(
                                                                           settings.AUTHENTICATION_BACKENDS),
    +                                                                  'next': request.GET.get('next')
                                                                   }))

**Comment by cjlee112** [comment]
@maxsocl Thanks for setting me on the right path, Maksim!  It required a little bit more, to properly handle both the GET and POST cases, e.g. if authentication fails we still need to pass 'next' through correctly...

**Comment by maxsocl** [comment]
@cjlee112 
  * Yes, exactly. This patch is handled the same case - it redirects user to a next url is case of fail auth so if user after fail auth will type correct credentials he will be redirected to a proper page.
  * But as I see you last commit pass `next` param both in GET and in fail auth POST request to a custom_login page to use in hidden input. So user will be redirected to next page after entering proper credentials. One misleading for user is changed address bar from `/login/?next=/ct/courses/1/units/1/` to `/login/`. May be it is better to redirect user to a next page in fail auth case? You can do this like in this [patch](https://gist.github.com/maxsocl/71f202f7f79c1d54aea3).

**Comment by cjlee112** [comment]
@maxsocl Hmm.  Redirecting a failed POST seems contrary to the standard Django / crispy practice of displaying error messages explaining what went wrong on the form, so the user can correct it.

**Comment by maxsocl** [comment]
@cjlee112 Yep, correct. So render login page with next param is a good idea. Additionally we need to provide error message for user.
