### ISSUE TITLE
Question not visible in ChatUI when preceded by non-ORCT lesson(s)

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#460]
The current ChatUI has two combined behaviors that I've found can confuse students: 

1. it doesn't show non-ORCT lessons one at a time (unlike ORCT lessons, which are always shown one at a time).  Instead it spits them all out at once, until it reaches an ORCT lesson, at which point it reverts to the one-at-a-time normal behavior.  I suspect the current implementation may not even have any upper limit on how many lessons it will try to spit out at the user all at once; it definitely will concatenate far more more material than will fit in the viewable region of the ChatUI.

2. when it spits out multiple lessons at once like this, it appears to keep the ChatUI scrolled to show *the first new lesson*, which often results in the question (that the student is now being asked) not even being visible on the screen (it is hidden down below the bottom of what's visible in the chat).  The student sees a "Type your answer here" prompt, but no question!  See the attached screenshot.

A very simple solution would be simply to present non-ORCT lessons one at a time (same as all the other lessons), e.g. by having the student click Continue as we do when showing error model resolutions.
![scrollissue](https://cloud.githubusercontent.com/assets/59820/25976729/a55ef1ac-366b-11e7-8773-dd2a5f8d98d4.png)

**Comment by redilonka** [comment]
@cjlee112 
The current behavior is exactly the same as you want to have.

![courseletsme1](https://cloud.githubusercontent.com/assets/15940935/26168003/4f2605de-3b41-11e7-9db3-e535eb51c8ef.gif)

**Comment by cjlee112** [comment]
@redilonka Unfortunately, I am still seeing the exact same problem (I am using in Firefox, in case that matters).  I just checked again, and the bug is the same as what I originally reported.  Here is the screenshot of what I see after starting a Courselet (by clicking the Let's Get Started button).
![issue460](https://cloud.githubusercontent.com/assets/59820/26168749/11edfdee-3af0-11e7-8c10-7bba43bc9054.png)

**Comment by maxsocl** [comment]
I've checked `Dynamic Programming Sequence Alignment` and cant reproduce this behaviour.

**Comment by redilonka** [comment]
fixed
