### ISSUE TITLE
Server error 404 on clicking Read More link

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#461]
Clicking Read More in this courselet leads to 404 Server Error.
https://www.courselets.org/chat/enrollcode/3d85b0b14d884815a9ffc5d1de645a76/
![readmore](https://cloud.githubusercontent.com/assets/59820/26013432/35ce9bd8-370d-11e7-9c06-8187cc17ff3e.png)
![error404](https://cloud.githubusercontent.com/assets/59820/26013436/3cedb818-370d-11e7-8897-4e195f57c229.png)

**Comment by maxsocl** [comment]
@cjlee112 This 404 error is coming from your Courselet settings:

<img width="534" alt="screenshot at may 13 14-34-56" src="https://cloud.githubusercontent.com/assets/877401/26025122/6668ed52-37e9-11e7-9cc4-4cbfd1781060.png">

**Comment by maxsocl** [comment]
I've changed this URL to https://www.courselets.org and everything works fine.
