### ISSUE TITLE
[Gaston] SyntaxError: JSON.parse: unterminated string

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#464]
Gaston was trying to generate report for his course 26 at https://www.courselets.org/ct/teach/courses/26/edit/, and got "SyntaxError: JSON.parse: unterminated string at line 542 column 19 of the JSON data"

A follow-up on issue #416

**Comment by maxsocl** [comment]
@xqrongm Cant reproduce this for any of your reports. Everything works fine for any reports.
I believe it was network error while you tried to download report.
