### ISSUE TITLE
[Gaston] student's progress not saved

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#465]
Gaston's student Mya Majewski stated that her progress in the PCR and Gel courselets are not saved. However, Gaston can see her progress as the following:

PCR
![image](https://cloud.githubusercontent.com/assets/12205732/26038964/ef3e2266-38e1-11e7-8914-f3d415aba51d.png)
Gel
![image](https://cloud.githubusercontent.com/assets/12205732/26038971/05852e0c-38e2-11e7-9e95-837cee1b5df6.png)

Here is the student's email:

> I did the Courselet this week that replaced the post-lab and I completed it twice but after I log back in to do it again it did not record the previous times that I have completed it.
> 
> Even for last weeks DNA Isolation lab as well I went back to that Courselet And my completion was not recorded as well. So, for the gel electrophoresis lab and DNA isolation lab it appears online that I have not completed the Courselet because no history of completion was recorded for both.

**Comment by maxsocl** [comment]
@xqrongm There is new Tab History for completer Courselets.
After completion Student can reDo Courselets clicking on main link to start Courselet.

**Comment by maxsocl** [comment]
@xqrongm please confirm that Student Mya Majewski can look at history tab. Thanks

**Comment by xqrongm** [comment]
Another student Marian Alino has a similar complaint. Here is her email:

LS 23

> L - PostLab Assessments
> 
> Good afternoon,
> I had already done the assessments for Lab E and F; however, when I click the link to the assessments again, my attempt has not been saved. This worries me because I am unsure if I will be getting points for the assessment or not. Is there any 

way for me to check this?

**Comment by maxsocl** [comment]
@xqrongm thanks

**Comment by xqrongm** [comment]
Marian Keiko Alino said that she was able to click on "Courselet HIstory", and her past courselets, the PCR and GEL appeared, which is good. But the issue still needs to be addressed that they were confused about progress not saved. I asked the students "what screen did you see that made you believe that your progress was not saved?", waiting for response.

**Comment by xqrongm** [comment]
Sometimes when students goes to a courselet from the "Courselets" tab on a course page, they have to start over, though their previous progress was saved under the Courslet History tab. After they start over that way, their new progress doesn't seem to be saved and updated under the Courslet History tab.

**Comment by xqrongm** [comment]
I tested it out on my own. This is my understanding:

When a student complete a courselet, this record show up in the history tab. Then if a student go to the courselet from the "Courselets" tab again, it starts over as a new round. So you can complete a courselet multiple times, and they are recorded as separate history entries. If you leave the platform before you complete a courselet, your progress is saved, and you can start where you left off when you come back. It's not logged into the history tab until it's completed.

I think this behavior is fine, but it may be a little confusing to students if they don't look at "Courselet History" tab, and just start over and thought they lost the progress. We may need to discuss how to avoid this confusion.

Also, after students start on a courselet and before complete it, if they leave and come back, they will see the beginning of the courselet instead of where they left off, they have to scroll all the way down to see where they left off. This may be confusing to the students too, and at the first glance some may think they lost their progress and have to start over.

Last, someone may already noticed, the "Courselet History" tab is misspelled as "Courslet History", missing the "e" after "s".

**Comment by xqrongm** [comment]
Gaston brought up the concern that since students are allowed to complete a courselet multiple times, it may generate too much data for him to look at.

Is it possible to generate report for instructors only including the data first time each student complete the courselets?

**Comment by maxsocl** [comment]
@xqrongm Now only last Student response is included in report for each Lesson.
Do we want to change it to include only first?
Thanks

**Comment by xqrongm** [comment]
@maxsocl Yes, I think "only first" makes more sense, because it reflects the misconceptions and misunderstandings of students, which instructors would like to know about. Thanks.

**Comment by alexbojko** [comment]
Wee need updates in API and in reports too.

**Comment by alexbojko** [comment]
pushed to branch fix/issue#465. needs review

**Comment by alexbojko** [comment]
I generated report before changes and after them. 
Here we can see the difference between them.

[new report](https://staging.courselets.org/media/reports/responses/f3f11d0ca40743278048b7fb48aba21b.json
)
[old report](https://staging.courselets.org/media/reports/responses/291/5ac489b6915947b9a8383d19c74161d1.json)

**Comment by redilonka** [comment]
@alexbojko @rimikt 

1) generate report
2) update my answer in course
3) The first answer was cleared and we view the last answer

**Comment by redilonka** [comment]
verified on stage

**Comment by redilonka** [comment]
verified on prod
