### ISSUE TITLE
[Gaston] The link for students listed in the CCLE (LTI) is the courselt not the course

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#466]
Gaston said:

> The link for students listed in the CCLE (LTI) is the courselt not the course right now:
> e.g.
> PCR https://www.courselets.org/lti/ct/courses/26/units/145/
> GEL
> https://www.courselets.org/lti/ct/courses/26/units/146/
>  
> So students don’t land on the course page right now and would have to navigate to it.
> Why is this different now?
> What changed?

I have no access to CCLE and I don't know how Courselets platform is connected to CCLE, so I don't quite understand what he's talking about. I tried the two links he mentioned, both led to "Error: LTI request is not valid" for me.

**Comment by xqrongm** [comment]
Just for my own information, what does "lti" and "ct" mean?

**Comment by maxsocl** [comment]
@xqrongm nothing changed. This is an old behaviour - User will be redirected to Courselet view with such links.

**Comment by maxsocl** [comment]
Link should be `https://www.courselets.org/lti/ct/courses/26/`

**Comment by xqrongm** [comment]
@cjlee112 @maxsocl I don't have access to CCLE to test out the links in CCLE, and I don't know enough about how CCLE connects to Courselets platform to understand either side of the conversation (Gaston or Maksim). Is there anything can be done to help me understand this system so I can better support the instructors? For example, give me access to CCLE and/or a quick overview of the design that connects CCLE and Courselets. Thanks.

**Comment by xqrongm** [comment]
Gaston has some follow-up questions and comments:

> So I posted a link on CCLE pointing to the course site instead of to the courselet and send a message to the students.
>  
> This is fine now.
>  
> When did this change happen?
> Will students be able to take the corselets repetitively?
> Is there a setting I can chose if students can retake the courselet?
>  
> I have listed a few test-lets under my account can we delete these from the system?

**Comment by maxsocl** [comment]
@xqrongm I have no access to CCLE :(

> When did this change happen?

Nothing was changed last few months.

**Comment by xqrongm** [comment]
@maxsocl ok no problem. Would you be able to tell me what "LTI" and "ct" in the URL mean? Does it have anything to do which how Courselets platform is connected to CCLE?
