### ISSUE TITLE
Answers table for 40-student course shows hundreds of (wrong) students

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#468]
Just tried the new Answers tab on one of my courselets, and got an insane result.  There are only circa 40 students in my course, but the table on the Answers tab shows hundreds of people, who are definitely not enrolled in my course.  Something is horribly wrong with the database query for generating this table.  This could also explain why it was horribly slow (took 10 seconds for the page to appear).  Here is the URL that shows this wrong result:

https://www.courselets.org/ct/teach/courses/25/units/123/answers/

@xqrongm Is Gaston also affected by this bug?

**Comment by xqrongm** [comment]
I don't have access to the "teach" pages of Gaston's course, but my own dummy course seem to have the same problem. At https://www.courselets.org/ct/teach/courses/21/units/107/answers/, the majority of the rows are the users definitely not enrolled in my dummy course and have no data for the answers to my courselet.

**Comment by maxsocl** [comment]
@xqrongm @cjlee112 Fixed as a hotfix.

**Comment by xqrongm** [comment]
It works properly now for my dummy course 21. Thanks!
