### ISSUE TITLE
The multilple objects error appears

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#473]
STR:
1. Invite user through UI
2. Assign the role to user through admin panel
![error](https://cloud.githubusercontent.com/assets/11578840/26245951/6b57f848-3c9f-11e7-960d-45ccf6d73807.png)

**Comment by alexbojko** [comment]
I need to know steps how to reproduce this bug, because this screen shows only effects of this bug, but I don't know how come to this

**Comment by DenisKolesnik** [comment]
@alexbojko 
Looks like we have an issue only with particular course:
https://dev.courselets.org/lms/courses/5/

if this course shared with any tester and then open it in /ctms - the error is reproduced
