### ISSUE TITLE
The error appears when trying to add a unit by a chat

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#478]
STR:
1. Add unit by a chat and take a look at the messages and "Something wen wrong error message"
![add_unit_by_chat](https://cloud.githubusercontent.com/assets/11578840/26311946/aea11fd2-3f0e-11e7-9cd4-b9dc08b9c659.png)

**Comment by alexbojko** [comment]
@DenisKolesnik this ticket is no more reproducible.

**Comment by DenisKolesnik** [comment]
Fixed
