### ISSUE TITLE
The remove error model link doesn't delete error model

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#479]
STR:
1. Add a unit with error model 
2. Delete error model in unit

ER: The unit is deleted
AR: The page is just scrolled tot he top
![remove error](https://cloud.githubusercontent.com/assets/11578840/26312102/3ebcb112-3f0f-11e7-9bd4-dec858895bb9.png)

**Comment by cmltaWt0** [comment]
Fixed
