### ISSUE TITLE
The predefined error models appears in the unit preview

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#480]
STR:
1. Open unit preview page and take a look at the error models list

ER: There aren't predefined models in the unit preview window
![predefned errors](https://cloud.githubusercontent.com/assets/11578840/26312651/f77b7f20-3f10-11e7-80ba-6b95e20627b9.png)

**Comment by cjlee112** [comment]
Still seeing this behavior in the Instructor Preview, so I assume it's also happening in the student Chat UI.

**Comment by rimikt** [comment]
Fixed.
