### ISSUE TITLE
The incorrect notification appears when saving unit with empty fields

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#484]
STR:
1. Try to save unit with empty fields and take a look at the error message 

ER: Fields which filled with incorrect inputs should be highlighted
![notifications](https://cloud.githubusercontent.com/assets/11578840/26315161/e8a9f8ac-3f18-11e7-83b0-a76ff82aa623.png)

**Comment by cmltaWt0** [comment]
Fixed
