### ISSUE TITLE
The error appears when student opens /ctms page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#487]
STR:
1.  Delete instructor through console

**You can view error by loginning to this user:**
login - jrir@arurgitu.gq
pass - qwerty

![error](https://cloud.githubusercontent.com/assets/11578840/26356273/3a6ea73a-3fd4-11e7-8e00-79c23dd048a4.png)

**Comment by cmltaWt0** [comment]
Fixed
