### ISSUE TITLE
The instructor answer doesn't appear in Chat when adding unit by a chat

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#489]
STR:
1. Start adding unit by a chat and take a look at the instructor answer in chat ui

ER: the answer appears in chat ui
![answer](https://cloud.githubusercontent.com/assets/11578840/26394198/c99d59c4-4074-11e7-849d-e30f9cc3dcec.png)

**Comment by cmltaWt0** [comment]
Not relevant for now
