### ISSUE TITLE
The error appears in the chat and it's impossible to finish it when completing a chat in two tabs

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#495]
STR:
1.  Open a chat in the 2 diferent tabs
2. Answer on a few questions in first tab and then proceed to the second and answer on the question on which you just answered

AR: The "smthng went wrong error" appears and it's impossible to finish the chat
ER: The error message appears when user want yo answer on just answered questions
![error](https://cloud.githubusercontent.com/assets/11578840/26406729/d1aae712-40a1-11e7-8940-1cd8a7af8e02.png)

**Comment by redilonka** [comment]
I reproduce it.
