### ISSUE TITLE
[4] Invite tester - Email - Invited to test a course in the Instructor Web App ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#504]
https://karluxd.atlassian.net/wiki/display/COUR/Email+-+Invited+to+test+a+course+in+Instructor+Web+App 

* User should be redirected to “4. Sign up” (nice if we could prefill the email address here). 
* If we can check for existing accounts, those users should be redirected to the login page

**Comment by alexbojko** [comment]
@maxsocl , @cjlee112 
I will implement this logic:
* if user is not authenticated - redirect to signup page
* if user is authenticated:
  * check user's email:
    * if user is present in DB - show login page with pre-filled email
    * if there's no such user - show signup page with pre-filled email
* in any other cases - redirect to signup page with no pre-filled email field

**Comment by DenisKolesnik** [comment]
1. If user doesn't have an account - the login page opens (ER: redirect to signup page )
2. if user has account - the login page appears without prefill email
3. If user has account and logged in - the 404 error appears when open the link from email
