### ISSUE TITLE
[8] Invite tester - SignUp - Skip confirm email for invited users ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#505]
https://karluxd.atlassian.net/wiki/display/COUR/4.+Sign+Up 
Skip confirm email for invited users.

STR: 
* invite new tester. 
* logout
* Open link from email. 
* it will redirect to signup/login page
* signup
* user will receive confirmation email (this is wrong!!!)

ER: user not receive confirmation email. 

in proxy view:
* create hash, write it to session
* render signup page with hash in form
* in signup view check hash from form and skip confirmation email step if hash is the same and do login immediately 
* tests?

**Comment by DenisKolesnik** [comment]
The email confirmation isn't present for invited user's for now

**Comment by DenisKolesnik** [comment]
Fixed
