### ISSUE TITLE
[2] Invite tester - Signup - Redirect after signing up ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#506]
It should redirect to “1.2 Shared with me” after they’ve signed up.

STR: 
* invite tester
* logout
* open link from tester's invitation email
* signup
* observer link after signup

ER: shared courses

if we have hash in signup form - redirect user to shared courses

**Comment by DenisKolesnik** [comment]
The 404 page appears after opening the link from email
