### ISSUE TITLE
[3] Social form wrong template ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#507]
https://karluxd.atlassian.net/wiki/display/COUR/4.2+Social+Form 

Wrong template and missing description, see https://projects.invisionapp.com/share/4XAQVN2MA

**Comment by DenisKolesnik** [comment]
The error appears when signup through social account http://prntscr.com/fggjdf

**Comment by DenisKolesnik** [comment]
Fixed
