### ISSUE TITLE
[2] Invite students page

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#508]
AR: redirect user to a separate page after the invite has been sent. 
ER: We should show a success message below the topbar, not redirect them after invite successfully sent

**Comment by DenisKolesnik** [comment]
http://prntscr.com/fgfxoz success message appears and looks correctly aftee sending invitation.
Relevant only for Tester's. Student invitation doesn't implemented yet

**Comment by cmltaWt0** [comment]
Fixed
