### ISSUE TITLE
Courselets and Units are always marked as active

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#509]
Courselets and Units are always marked as active. 

They should only have a border when you view those pages. 
Also, Share and Settings are missing the border when they’re active

**Comment by karluxd** [comment]
@alexbojko The class names are already there. Someone that knows the backend just needs to check what page we're on and highlight the correct links in the sidebar. When I tested this, courselets and units were always marked as active 🙂

**Comment by DenisKolesnik** [comment]
@alexbojko 
![border](https://cloud.githubusercontent.com/assets/11578840/26672469/f8a5ed82-46c1-11e7-9fb7-c8891c0c2ec4.png)

**Comment by karluxd** [comment]
Thanks for the image @alexbojko, the class used to be there 🙂 

```
<li>
    <a class="sidebar__units__active" ...
```

**Comment by DenisKolesnik** [comment]
it's necessary to add highlighting a unit to unit settings and edit screens also

**Comment by DenisKolesnik** [comment]
The page of the opened page is highlighted now
