### ISSUE TITLE
Add PostgreSQL installation section to Socraticqs2 documentaion

### ISSUE THREAD

**Issue by maxsocl** [cjlee112/socraticqs2#51]
Goals
--------
We need to give a new developer a manual to quickly start to work on project with PostgreSQL DB

Requirements
------------------
1. Typical process to install PostgreSQL on linux PC (e.g. Ubuntu 14.04 dist)
2. Steps to set an internal `postgres` user password
3. Steps to create a new database
4. Steps to configure Django project and give access to PostgreSQL from a project
5. Link to Mac OS X documentation to install PostgreSQL

Task on [trello](https://trello.com/c/Mrtja0pi/187-add-postgresql-installation-section-to-socraticqs2-documentaion).
---------------------

**Comment by cjlee112** [comment]
See additional doc update requirements in my comments on PR #45

**Comment by maxsocl** [comment]
> See additional doc update requirements in my comments on PR #45

Yeap, ofc I will update documentation.
But I need to spent some time to test `backup`, `sqlflush` etc. operation on Postgres.
So I think it will be better to create a new issue. Espessially because of https://github.com/cjlee112/socraticqs2/pull/45 has been closed.
