### ISSUE TITLE
[3] Invite testers - Login flow ()

### ISSUE THREAD

**Issue by alexbojko** [cjlee112/socraticqs2#510]
Pass next from signup page to login

If hash is in signup form - change login page url to pass next (to redirect user to shared with me page)

**Comment by DenisKolesnik** [comment]
The /signup/?next=/ctms/ part of url is present on the sign up page

STR:
1. Without logining Go to /ctms page (make sure you see "?next=/ctms/" in the url)
2. Proceed to signup page and make sure that "?next=/ctms/" is prsent on the signup page
