### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#522]
1. The "none" username in the confirmation letter 
2. The "Key Error" error appears when trying to change name

**Comment by alexbojko** [comment]
KeyError is fixed and dev is updated

**Comment by alexbojko** [comment]
@DenisKolesnik , username none in confirmation email also fixed. 

Added fixes to pass more data to page /ctms/email-sent/ 

@DenisKolesnik pls check this functionality:

STR:
* logout
* signup but not click on link from confirmation email
* click Resend email
* observe email 

ER: username must not be None, it must be correct

**Comment by alexbojko** [comment]
@DenisKolesnik dev server is up to date

**Comment by DenisKolesnik** [comment]
The "none" username in the confirmation letter - FIXED
The "Key Error" error appears when trying to change name - FIXED
