### ISSUE TITLE
It's impossible to signup to Courselets

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#542]
STR:
1. Signup to platform entering Email
2. Proceed by a link in email and take a look at the warning message

ER: User is registered in the system
AR: User isn't signed up to system
![errpr](https://user-images.githubusercontent.com/11578840/27122540-b9b89c78-50f3-11e7-91a3-b2c29cba2659.png)

**Comment by maxsocl** [comment]
Fixed

**Comment by DenisKolesnik** [comment]
FIXED
