### ISSUE TITLE
The error appears when trying to open finished courselet

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#549]
STR:
1. Open completed courselet

http://dpaste.com/13V4XE7

https://staging.courselets.org/chat/enrollcode/dc0ec2089ef7483c94646c738817ba7b/

![error](https://user-images.githubusercontent.com/11578840/27277349-a0e91a3c-54e6-11e7-8f60-7877ccdbaa60.png)

**Comment by alexbojko** [comment]
fixed and pushed to development branch. commit bb6ec8982a96097ff7d0ae21108e5b6fc8620d92

**Comment by DenisKolesnik** [comment]
FIXED
