### ISSUE TITLE
The signup button doesnt work on landing page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#559]
![s](https://user-images.githubusercontent.com/11578840/27341676-9b84c52c-55e6-11e7-94c5-a5329905d07b.png)

**Comment by alexbojko** [comment]
Fixed in PR #560

**Comment by DenisKolesnik** [comment]
It's possible to link in new tab, but impossible just by clicking the button. Some issues with JS...

**Comment by DenisKolesnik** [comment]
FIXED
