### ISSUE TITLE
The instructor redirects to old ui shen clicking on preview in courselet which doesn't have any unit

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#565]
STR:
1. Create empty courselet 
2. Open it and open the preview 

ER: The warning message appears if courselet doesn't have any unit
![p_1](https://user-images.githubusercontent.com/11578840/27483696-2ebfda08-582f-11e7-9e62-097398339d3b.png)
![p_2](https://user-images.githubusercontent.com/11578840/27483695-2ebfe566-582f-11e7-91d5-20874883c8b8.png)

**Comment by cmltaWt0** [comment]
Fixed by disabling preview button when there are no lesson.
