### ISSUE TITLE
Add sidebar scrolling

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#566]
The sidebar isn't scrolled when list of unit creation steps reaches the end of display

ER: Sidebar is scrolled when new step is added to it after reaching the end of the display
![add_scrolling](https://user-images.githubusercontent.com/11578840/27484597-7d27db84-5832-11e7-896c-58a24575b6c8.png)

**Comment by maxsocl** [comment]
@karluxd ^
