### ISSUE TITLE
Divide units in the sidebar

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#567]
The steps in the sidebar looks unsorted. Each unit should have separator from another
ER: The separator  line appears between new and previous unit
![divide units](https://user-images.githubusercontent.com/11578840/27484696-da4f0a30-5832-11e7-840a-bdb24fcfa1ca.png)

**Comment by DenisKolesnik** [comment]
@karluxd Karl, Do you have any design/ideas how to implement it?

**Comment by karluxd** [comment]
@DenisKolesnik I think it's fine for now. Let's try it out and see what users think and if we should keep it first.
