### ISSUE TITLE
Line return not shown as-is in FAQ edit page

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#572]
https://www.courselets.org/faq/?edit

The FAQ page doesn't seem to allow me to show line return. For example, I put in content in editing window like this:

![image](https://user-images.githubusercontent.com/12205732/27693237-d81a6d3a-5cb6-11e7-8930-49c7d6f8406c.png)

but once it's published, line returns disappeared

![image](https://user-images.githubusercontent.com/12205732/27693269-ee8f08dc-5cb6-11e7-839b-90e112d61615.png)

Is it possible to show line returns in the published view? Thanks!

**Comment by DenisKolesnik** [comment]
@maxsocl The markdown isn't used in the FAQ page plugin. Maybe we should use it to show question/answers correctly?

**Comment by DenisKolesnik** [comment]
The git makdown was added to FAQ page plugin
