### ISSUE TITLE
[Gaston] New instances of a courselet for different quarters/semesters

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#573]
Instructors would like to create new instances of the same courselet for different quarters/semesters, where the courselet contents are copied while the students' data start over. Also need to assign new courselet instances to new courses

"Question" label is attached in case discussion is needed for the details of implementation.

**Comment by xqrongm** [comment]
@maxsocl Gaston would like this for the upcoming summer quarter. Can I have a time frame in regards to when this can be implemented? I'll let Gaston know about it, so he can decide whether he wants to wait for the implementation or manually copy the contents over. Thanks!

**Comment by xqrongm** [comment]
I attached the "Critical [Severity]" label because I received feedback from instructors that they are in urgent need of this feature. Without this feature, it is very frustrating for them to spend hours to manually recreate the same courselets for each new quarter/semester. Thanks!

**Comment by rimikt** [comment]
@xqrongm To clarify our required specification - we need to be able to duplicate all previous content as well as to add new content (new Courselet(s))?
thanks.

**Comment by rimikt** [comment]
@xqrongm Give me deadline for instructors to have this feature please.

**Comment by xqrongm** [comment]
@rimikt Yes. We need to be able to duplicate all the existing contents in the unit of a courselet, i.e. duplicate all the lessons and resources of a courselet in one operation. This feature also needs to work for newly added courselets. 

In terms of deadline, if it's easier for you to delete all the student data associated with Gaston's course 26, so he can re-use it for the upcoming quarter, please do so. Then maybe fix this issue in the next release if possible? Thanks!

**Comment by xqrongm** [comment]
The test copy of my "Xiaoqing example course" looks good! Can we make a copy for Gaston's course 26? Then I'll ask him to check if everything is copied correctly? Thanks!

**Comment by redilonka** [comment]
@xqrongm 
Clone course 26 done.
New Course id is 37.

**Comment by xqrongm** [comment]
Gaston said that the everything seems correct in the new course 37. He suggests that the newly copied courselets should be unpublished, i.e. not accessible to students, whether the original courselets are published or not. I think it's a good point. Thanks!

**Comment by rimikt** [comment]
Done

<img width="1122" alt="screen shot 2017-08-10 at 11 25 54 am" src="https://user-images.githubusercontent.com/877401/29161390-b5abd77e-7dbe-11e7-9477-723fa6cac75e.png">
