### ISSUE TITLE
[Gaston] lessons missing

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#596]
Gaston reported that some of his lessons are missing. We believe that he didn't do anything that could cause this. Can someone please investigate what happened? Thanks!

https://www.courselets.org/ct/teach/courses/26/units/145/lessons/
Lesson 4 (order 5) is missing.
![image](https://user-images.githubusercontent.com/12205732/28119983-b31a312c-66e4-11e7-950a-bdbd305f4ab5.png)

https://www.courselets.org/ct/teach/courses/19/units/144/lessons/
Lesson 4 (order 4) is missing.
![image](https://user-images.githubusercontent.com/12205732/28120034-dbbed826-66e4-11e7-9cf2-da244c0f3ce1.png)

https://www.courselets.org/ct/teach/courses/18/units/98/lessons/
Lesson 1 (order 1) and Lesson 4 (order 4) are missing.
![image](https://user-images.githubusercontent.com/12205732/28120106-16022fa6-66e5-11e7-903b-29403ac5402f.png)

**Comment by xqrongm** [comment]
no trace in log, sorry

**Comment by rimikt** [comment]
@xqrongm 
Here is a link to add missing Lesson into Courselet:
https://www.courselets.org/ct/teach/courses/26/units/145/lessons/6991/

**Comment by xqrongm** [comment]
@rimikt Thanks for the link! When instructors notice their lessons are missing, how can they find links like this and add the lessons back to the courselets?

**Comment by rimikt** [comment]
@xqrongm In no way - you need to open an issue so we will help you to find missing lesson.
