### ISSUE TITLE
Resolution doesnt appear after completing unit lesson to "select error model" step, closing the chat and opening it again

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#601]
STR:
1. Complete unit lesson to "select error model" step
2. close the chat
3. open it again and select error model with resolution and click continue

ER: The resolutions appears
AR: The unit lesson is fisnihed 
![p5rqvig6tgsz1qr5d8opzg](https://user-images.githubusercontent.com/11578840/28218562-8efebd38-68c1-11e7-8dc5-b98aca483805.png)

**Comment by cmltaWt0** [comment]
Not relevant
