### ISSUE TITLE
[Gaston] student completed the courselet but progress not shown correctly on student's end

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#602]
Is this related to https://github.com/cjlee112/socraticqs2/issues/465?

Gaston's Course 32 "", Courselet unit 161 "", student "PETER SEDAROS".

The student finished the courselet, as shown in instructor's view (https://www.courselets.org/ct/teach/courses/32/units/161/answers/)
![image](https://user-images.githubusercontent.com/12205732/28220576-054e4b18-688e-11e7-920b-19e249631b19.png)
![image](https://user-images.githubusercontent.com/12205732/28220594-14b4b20e-688e-11e7-8488-fd243a822c61.png)

However, on the student's end, it shows that he just started Lesson 1, which is not true.
student's view 1:
![image](https://user-images.githubusercontent.com/12205732/28220700-7a167e8e-688e-11e7-8ce7-9aacae6048db.png)
student's view 2:
![image](https://user-images.githubusercontent.com/12205732/28220729-946c101e-688e-11e7-8ccd-8cd68183c88c.png)

**Comment by DenisKolesnik** [comment]
@xqrongm 
The answers show that student complete courselet on July 14, but your screen shows 13 July session. It's just another session which was started by the student but wasn't finished.

**Comment by xqrongm** [comment]
@DenisKolesnik I can't see from the student's view, so it's hard for me to show him what you are talking about. Would you be able to see from his view and post a screenshot here? I'll use it to explain it to him.

**Comment by xqrongm** [comment]
I tested with my own example course and found out what's wrong. 

The "MY HISTORY" section in the "Courselets" tab shows the wrong progress:
![image](https://user-images.githubusercontent.com/12205732/28270495-a9859a0a-6ad3-11e7-8316-2b156f7a20b3.png)

While the "Courslet History" tab shows the correct progress (btw the typo should be fixed as "Courselet" instead of "Courslet"):
![image](https://user-images.githubusercontent.com/12205732/28270519-ccc75b84-6ad3-11e7-8485-fa441b58e11c.png)

These two places should show the same progress. Thanks.

**Comment by xqrongm** [comment]
Another student Alexa Sheldon also reported the same problem.

**Comment by DenisKolesnik** [comment]
@xqrongm 
The "MY HISTORY" section in the "Courselets" tab shows current progress of all unfinished/active sessions for now. Student can create unlimited amount of sessions with different progress and continue or finish them in any time.

While the "Courslet History" tab shows the completed sessions which student just can view.

There is only one issue here which explains, why students don't understand why they progress is zero.
System always creates a default sessions with zero progress in case student doesn't have any active session. And when student complete Courselet - this courselet moves to "Courslet History" tab on the Course page and disappear from the "MY HISTORY" section.
(FE: Student open courselet in first time -> He will see default session with zero progress; Student finish the courselet -> He also will see the default session with zero progress, but student can open courselets history tab on the Course page and see that he has complete session)

We have already reworked this flow to make it more understandable and obvious and work on implementation now.

**Comment by DenisKolesnik** [comment]
@xqrongm 
Here is screens from Peter Sedaros view:
1. Student history page
![1](https://user-images.githubusercontent.com/11578840/28311545-ae1a2c76-6bb8-11e7-929c-f2a319fa25c4.png)

2. Student answers 
![2](https://user-images.githubusercontent.com/11578840/28311552-b3829112-6bb8-11e7-8033-11b48d3a8585.png)

3. Student chat
![3](https://user-images.githubusercontent.com/11578840/28311558-b8d4a614-6bb8-11e7-9fd5-3270e9744223.png)

**Comment by xqrongm** [comment]
Courselet unit 161 seems to have been unpublished, thus cannot be accessed when I logged in as the student "PETER SEDAROS".

**Comment by xqrongm** [comment]
I published the courselets temporarily just to check it from the student's view ("PETER SEDAROS"). It shows completed sessions in the "MY HISTORY" section of each courselets, i.e. there doesn't seem to be a problem anymore. Maybe some changes you guys made to the platform fixed this issue? Anyway, it looks good now.
