### ISSUE TITLE
Multiple Choices feature

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#604]
Student
1. As a student i want to select single or multiple choices in one question
2. As a student i want my answers to grade according to selected correct/incorrect choices

Instructor
1. As instructor i want to add multiple choice questions:
   - More than two choices should be added
   - I want to edit correction of each choice (correct/incorrect choice)
2. As instructor i want to see choices which were selected by a student;
3. As instructor i want to see student grading according to selected choices;

**Comment by DenisKolesnik** [comment]
Feature isn't finished. moved to the next release

**Comment by karluxd** [comment]
@rimikt A summary of my discussion with @cjlee112 about this:

- Multiple choice is familiar and can make it easier for instructors to transition to Courselets.
- Multiple choice can easily be added as a new type of message in the instructor interface.
- We want to be careful and ensure that they only use multiple choice for things like pre and post-test assessment. We can explore more options later, but many of our core benefits would get lost if instructors replaced the ORCTs with multiple choice.
- The instructor should have the option to show the correct answer to the student at the end.
- An ORCT is formative – you learn from it. Multiple choice is summative – it only tests your understanding of something.
- The options will generally just be a sentence or two long, so we can design something that doesn't take up a lot of space.
- We can continue working on this when the instructor mvp is done.

**Comment by cmltaWt0** [comment]
Done
