### ISSUE TITLE
Change what to show on "Answers" page

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#606]
On the "Answers" page (https://www.courselets.org/ct/teach/courses/xx/units/yyy/answers/), the following changes are proposed to make it more user-friendly:

1. Don't show empty rows with just student's name without any answer data.

2. Don't show "Status" (e.g. value "No status" corresponding to "status": null in JSON report)

3. Show confidence (e.g. "confidence": "sure" in JSON report)

This is open for discussion.

**Comment by redilonka** [comment]
Done, except for `Don't show "Status" (e.g. value "No status" corresponding to "status": null in JSON report)`

**Comment by redilonka** [comment]
https://github.com/cjlee112/socraticqs2/issues/806
