### ISSUE TITLE
Allow instructors to generate course report

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#607]
On the course edit page (https://www.courselets.org/ct/teach/courses/xx/edit/), about the "Generate" button at the bottom that allows authors to generate reports for the course.

Please allow instructors (who are not authors) to generate reports too.

Maybe show who generated which report too, e.g. instead of "Download report from July 18, 2017, 8:04 a.m.", show "Download report from July 18, 2017, 8:04 a.m. generated by Xiaoqing Rong-Mullins"

**Comment by alexbojko** [comment]
change logic to check that user has a Instructor role in this course too. not only owner can generate reports

**Comment by rimikt** [comment]
@redilonka Feature is available on staging.courselets.org

**Comment by redilonka** [comment]
@alexbojko @rimikt 
I have two proposals: 
1) we need to re-render page when report is generated (or something like that)
2) we need open the report in a new tab

**Comment by rimikt** [comment]
@redilonka 
1.

**Comment by rimikt** [comment]
@redilonka 
2. Done

**Comment by redilonka** [comment]
check:

- [ ] allow instructors (who are not authors) to generate reports too. - done
- [ ] "Download report from July 18, 2017, 8:04 a.m. generated by Xiaoqing Rong-Mullins  - done
- [ ] we need open the report in a new tab - done
- [ ] report contains json.responses 
{
  `"status": "help", `
       ` "confidence": "notsure", `
      `  "unitLesson_id": 233, `
      `  "text": "\u3090 wi and \u3091 we are obsolete outside of Okinawan orthography.", `
     `   "courselet_id": 16, `
   `     "author_name": "Ilon\u043aa", `
       ` "submitted_time": "22-12-2016-14:57:02", `
       ` "selfeval": "correct", `
        `"author_id": 261, `
      `  "id": 170, `
        `"lti_identity": null`
    }
