### ISSUE TITLE
[Gaston] make time zone local to author

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#608]
#Gaston reported that he saw "18-07-2017" in JSON course report when it was 7/17 local time in LA. Please make sure all the time stamps are in time zones local to the authors of the courses, because instructors use them to determine if students finish the assignments before the deadlines. 

This is high priority because Gaston has students doing assignments on Courselets now. If this can't be implemented soon, just let us know what time zone it is for the JSON course report, so Gaston can adjust it to his local time accordingly. Thanks!

In the future, there may be instructors from other time zones than Pacific Time using Courselets. So maybe add a feature to determine the local time zone of users and show time stamps to them accordingly.

This is open for discussion.

Update all places where user can see timestamp to show timestamp+tz.
Update course report generation function:
 * pass user timezone to report generation function 
 * add link to user by id - put reports file in {user_id}/report_name
 * update timestamps in report according with tz

**Comment by alexbojko** [comment]
we need to check that it works correct

**Comment by alexbojko** [comment]
http://prntscr.com/g3yajv

it displays my local time when I look for report time.

But inside of report time is shifted down.

http://prntscr.com/g3yb2w

So, I can say - it works correctly. For now... (once we will have instructors in more than one TZ we will need to do changes)

**Comment by xqrongm** [comment]
Thanks everyone for making this happen! I guess this hasn't gone live yet so I can't test it. 

The local time applies to both the text like "Download report from Aug. 5, 2017, 12:08 a.m." and inside the JSON content of the report?

Also, I wonder if it's difficult to specify the time zone along with the time stamps? e.g. 11 am UTC-4:00, 8 am UTC-7:00 etc. - so that each user will know if it's in his/her own time zone by just looking at the time stamp itself, instead of having to verify with their clock. Thanks again!
