### ISSUE TITLE
The additional default error models are added to original course after course copy

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#612]
STR:
1.Copy a course
2. Open lesson with error models in originals course (lesson should have more than 1 and less than 5 error models)
3. Compare list of error models between original course and copy of it

ER: The list of error models is the same
AR: The list of error models is different 
![copy](https://user-images.githubusercontent.com/11578840/28463613-e912770c-6e29-11e7-9750-25ff7bb00a05.png)

**Comment by alexbojko** [comment]
as we decided with Denis, this is not an issue, I think this Error Models are linked to this UL because some students  check them (i found this in ct/views.py). @DenisKolesnik , I think we should close this ticket.

**Comment by DenisKolesnik** [comment]
Fixed
