### ISSUE TITLE
 Implement the button "version" for the parent-course

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#618]
STR:
1. Open error models page and search for any error model
2. Take a look that list of errors contains error models from another courses

ER: Instructor see error models attached only to current course
![errors](https://user-images.githubusercontent.com/11578840/28615287-43878292-7201-11e7-87fc-d504cd7013b0.png)

**Comment by alexbojko** [comment]
Implement it like it work on this page [link](https://staging.courselets.org/ct/teach/courses/54/units/896/lessons/?searchType=lesson&search=basic&submit=Search)

**Comment by redilonka** [comment]
We implemented the button "version" for the parent-course, which shown child versions in this issue.
