### ISSUE TITLE
The menu alignment is different on different pages

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#619]
1. Compare menu between '/' , '/ct' and 'ct/teach/courses/1/' pages 

ER: The menu alignment is the same on each page

**Comment by alexbojko** [comment]
Landing.html should be inherited from portal.html. Copy Css from landing page to portal.html

**Comment by alexbojko** [comment]
pushed to branch fix/issue#619

**Comment by redilonka** [comment]
I see many variations (for other pages) (on a stage)

**Comment by redilonka** [comment]
I think we need markup dev
