### ISSUE TITLE
Add core app (ct) documentation

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#62]
## Goal

For developers to easily start working on project.
## Requirements (AC)
- Core app should be documented according to Django documentation style.
- Documentation should use models docstrings (as Django documentation) - core app code should be self-describing by docstrings.
- If some code not follow Django style this should be documented and described why and how.

Task on [trello](https://trello.com/c/cfZiidN9/196-document-code-app-ct).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480187584)

**Comment by maxsocl** [comment]
@cjlee112 

Points to describe in documentation as common integration part:
* Lesson's branching - main goal, how to use it.
* Lessons, Concepts and Wikipedia One-to-One relation - main goal of this relation and basic usage in Socraticqs2.
