### ISSUE TITLE
Landing page changes

### ISSUE THREAD

**Issue by rimikt** [cjlee112/socraticqs2#629]
Nice @maksim.sokolski! I have some feedback but it would be nice to hear what @chris thinks as well.

1. The hero title and description should trigger interest, i.e. how can Courselets help me (as an instructor) and what results have we seen.
2. CTA should be something like “Schedule a demo” and scroll down to the contact form.
3. Remove the sections “What you’ll get from this hackathon”, “Hackathon Description” and “Personal Guides”.
4. Update “I’m Interested in the hackathon” and explain that Chris will contact them for a personal demo if they submit their contact details.
3. Can we remove all links in the topbar and just show “Sign in” for guests?

[3:29] 
It would be nice if we copy the styling from this version instead (where it’s centered) and include that topbar http://conceptinventory.org/hackathon/

**Comment by redilonka** [comment]
@rimikt @karluxd have discussed:

- [ ] 1. when user anonymous in site he should see only login button in header (in right)
- [ ] 2. remove "Courselest" (in hero section) 
- [ ] 3. change text on the button "learn more" to "schedule to demo" (in hero section)
- [ ] 4. remove sections below hero section (`container clearfix` and `container`)
- [ ] 5. remove sections `Learn a new concept` now and `Challenge your understanding of bioinformatics / Big Data`
- [ ] 6. change sections `Courselets: make your mistakes your most powerful learning tool from Christopher Lee on Vimeo.` : remove video and put on `Data Drives Effective Decision-Making` slider with video (what you can find in a hackaton page)
- [ ] 7. remove field `Your Availability` 
- [ ] 8. send new requests to email to @xqrongm

**Comment by alexbojko** [comment]
what else we should to do:

* when I click on button schedule to demo on hero section it redirects me to login page. Is it correct behavior? What user will see after logging in?

**Comment by alexbojko** [comment]
@rimikt please check it out [here]( https://staging.courselets.org/landing/)

**Comment by DenisKolesnik** [comment]
1 - 7 items verified on stage

**Comment by karluxd** [comment]
@alexbojko @rimikt Here's the html and sass for the hero on conceptinventory.org/hackathon

```
<header class="hero" role="banner">
  <div class="inner">
    <div class="container">
      <h1>Title</h1>

      <p>Text</p>

      <a href="#" class="btn btn-large im-interested">Button text</a>
    </div>
  </div>
</header>
```

```
.hero {
  position: relative;
  padding: 0;
  background: #ccc url(../images/hero-bg.jpg) no-repeat center center;
  background-size: cover;

  .inner {
    padding: 170px 0 180px 0;
    font-size: 16px;
    line-height: 28px;
    text-align: center;
  }

  h1, p {
    color: #fff;
    max-width: 712px;
  }


  h1 {
    margin: 0 auto;
  }

  p {
    margin: 13px auto 35px auto;
  }

  .btn {
    margin: 0;
  }
}
```

**Comment by rimikt** [comment]
Done
