### ISSUE TITLE
[2] [Investigate] The progress bar is set to zero when student reaches a unit lesson with resolution ()

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#633]
STR:
1. Open a chat and reach a unit lesson with attached resolution
2. Proceed to resolution step and take a look at the progress bar

Expected result: Progress isn't changed
Actual result: Progress is set to zero
![2](https://user-images.githubusercontent.com/11578840/29163449-3266d786-7dc5-11e7-8f81-663255d4cc21.png)

**Comment by cmltaWt0** [comment]
Fixed
