### ISSUE TITLE
un-publish by default when copying courselets as part of course

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#635]
follow-up to #573

1. When making a deep copy of a course, can we give instructor the option to publish or unpublish the copied courselets, with default to the same status as the original?

2. If the above is too complicated to implement, we can make newly copied courselets unpublished, whether the original courselets are published or not.

Please let me know which of the 1 and 2 will be implemented. Thanks!

**Comment by DenisKolesnik** [comment]
Verified on stage

**Comment by rimikt** [comment]
@xqrongm 
Implemented w/ one note:
- courselets can be published (all) or unpublished (all)
- default state (as was in old course) not implemented yet

**Comment by DenisKolesnik** [comment]
The feature was implemented
