### ISSUE TITLE
The sorting of histories isn't correct

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#650]
STR: 
1. Create a few sessions and take a look at the sorting

ER: The most recent sessions appear in the top of the list
AR: The most recent sessions appear in the bottom of the active sessions
![sorting](https://user-images.githubusercontent.com/11578840/29352911-29cd437a-8271-11e7-9188-ed9f82fe9fed.png)

**Comment by cmltaWt0** [comment]
Fixed
