### ISSUE TITLE
The versions appears two times in the error model lists

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#658]
STR:
1. take a look at the versions button the page:
https://staging.courselets.org/ct/teach/courses/5/units/19/lessons/316/errors/?search=You+think+it+is+red%3F
![1](https://user-images.githubusercontent.com/11578840/29462877-75a4f008-8439-11e7-898f-d27a2b9e9a07.png)
![2](https://user-images.githubusercontent.com/11578840/29462880-77e8f166-8439-11e7-9cf2-f9377104138b.png)

**Comment by rimikt** [comment]
@DenisKolesnik please test with vanished data. Create a new EM and clone contained Course multiple times.
