### ISSUE TITLE
The horizontal scroll appears on landing page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#660]
![1](https://user-images.githubusercontent.com/11578840/29567725-be0107ea-8756-11e7-9e27-64b7edc757ed.png)

**Comment by DenisKolesnik** [comment]
Issue hasn't been fixed

**Comment by karluxd** [comment]
There's an empty section with negative margins causing this:

```
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="message-container">
    </div>
  </div>
</div>
```

Can this be removed @rimikt? 
If not, you can just wrap the section in `<div class="container"></div>`
