### ISSUE TITLE
[2] The Data Error appears when create 5 copy of a course ()

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#664]
STR:
1. Create a copy of a course, create copy of copy... (repeat 5 times)
ER: It's possible to copy of copy infinite amount of times
AR: Data Error appears on 5th copy 
![error](https://user-images.githubusercontent.com/11578840/29614952-d5e8fbec-8814-11e7-8707-e7bde62c4d86.png)

**Comment by rimikt** [comment]
Date of cloned course should be changed

**Comment by DenisKolesnik** [comment]
FIXED
