### ISSUE TITLE
[5] store student time zone somewhere in profile and render it in reports for an instructor ()

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#667]
A follow-up to #634 "Specify the time zone along with the time stamps in JSON course report". This feature won't be fixed due to some internal Django's specifics.
I (@rimikt) do not want to complicate code application.
May be we need to discuss different approach to achieve our goal.
Possible solution is to store Student timezone somewhere in profile and render it in reports for an instructor.

**Comment by rimikt** [comment]
TODO:
- registration
- login
- reports
- documentation
- tests

**Comment by DenisKolesnik** [comment]
Verified.
1. Timezone is updated one time when user Signin or SignUp to courselets. 
2. If TZ field is empty the defauld value (LS timezone) will be shown in reports
