### ISSUE TITLE
Trap with social auth "The given email address is associated with another account" exception.

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#69]
There is a rare situation that can lead us to the falling in trap where we cannot login or merge accounts because there are two django users in with the same email. This situation is possible if some social auth provider does not provide user email.
There is [diagram](https://docs.google.com/drawings/d/18gC2aEFREEZj8CuGAlK-K-9dFB4izONkFnl1xc46U84/edit) to describe this.
Task on [trello](https://trello.com/c/qqbaZo78/123-consider-the-case-of-two-django-users-with-the-same-email-what-to-do-when-login-with-non-existent-socialauth-with-such-email-now).

One decision is to ask user to validate email during social auth process.

**Important!** Possible solutions need to be analysed to resolve this issue without interruption into third party auth process.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480185852)

**Comment by mhipo1364** [comment]
I think you have more than one account with this `username`, see this: 
https://github.com/omab/python-social-auth/blob/master/social/pipeline/social_auth.py

read line 67 comment
