### ISSUE TITLE
[Gaston] students can't access a courselet "LTI request not valid"

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#695]
This problem happened with Courselet "SEQ Courselet" in Course 48 "UCLA LS23L Life Sciences Core Laboratories Fall 2017" (https://www.courselets.org/chat/enrollcode/ea073b42d4e24c29993e1cdf43a18e27/).

At least two students are affected:
PABLO LOPEZ-VERON, guillermo.h.veron@gmail.com, 9aa8fecc64aee7247c0d334a2da935
STEVEN BARNETT, stevenbarnett1@live.com, 1355c57980582b71b28a77aa348db9

Both students reported that they were not able to access this courselet. STEVEN BARNETT reported error "LTI request not valid".

I logged in from Courselets admin page as the student for both of them, but was able to access this courselet. If this error happens when students tried to access Courselets from their UCLA accounts, I won't be able to replicate that process because I do not have a UCLA account.

**Comment by rimikt** [comment]
@xqrongm 

LTI Consumer is configured incorrectly:
`ERROR 2017-12-10 23:56:29,767 Consumer with key None was not found.`
Somebody need to check Moodle External Tool configuration.

**Comment by rimikt** [comment]
@xqrongm Can we close this bug

**Comment by xqrongm** [comment]
@rimikt Hi Maxim, my contract with Courselets ended a while ago, so I haven't kept up with the development and instructor, sorry! Maybe you can contact Deborah and see who's in charge of support now.
