### ISSUE TITLE
Update landing page texts.

### ISSUE THREAD

**Issue by karluxd** [cjlee112/socraticqs2#696]
We should update the landing page to welcome instructors that are participating in the trial. Is this something you want to write @cjlee112? Here's a rough outline of what I had in mind:

**Welcome to Courselets**
A sentence or two about the trial and how Courselets can help them and their students.
Get Started

This is the template we'll use: https://staging.courselets.org/

**Comment by rimikt** [comment]
@karluxd Landing page is CMS page - so you can change the text directly in admin page.

**Comment by cmltaWt0** [comment]
Need to review current landing page for Onboarding release.
