### ISSUE TITLE
The landing page button should redirect to the login page.

### ISSUE THREAD

**Issue by karluxd** [cjlee112/socraticqs2#698]

**Comment by rimikt** [comment]
Please describe.
Button for Anonymous user should redirect to the login page and for LoggedIn user to another place?
We can do this.
Please confirm.

**Comment by rimikt** [comment]
Done

**Comment by karluxd** [comment]
Looks like this is working. @cjlee112 should the text in the button be "Engage"? Maybe we should use something more common instead, e.g. "Get started". I think this would make sense for both guests and users that are already logged in.
