### ISSUE TITLE
Instructor preview oddities

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#706]
When the instructor enters answers into the preview, their name then appears in the old UI Answers table (but with all answers blank).  Presumably answers entered in the preview shouldn't be saved at all.

It also wasn't clear to me how the Instructor is supposed to end a preview chat, since there was no explicit control to do that.  Just close the browser tab?  When I tried that, seemed to leave the session in a weird state (gave me old FSM message "you are currently in the middle of an activity..."  Thought we got rid of that).

**Comment by redilonka** [comment]
checked
