### ISSUE TITLE
ReStructuredText, not Markdown

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#708]
Edit Thread page says "You can use Markdown" and provides link to a Markdown tutorial.  But we don't use Markdown.  We use ReStructuredText.

**Comment by cjlee112** [comment]
Possible ReST cheatsheets to link to:

* https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html
* http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

I suspect we should make our own ReST cheatsheet that focuses on features most useful for Courselets.

**Comment by rimikt** [comment]
Fixed.
Use second link.
