### ISSUE TITLE
Make sure that caching not applied to pages with changing results

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#71]
Especially for the instructor interface (where the instructor may be rapidly adding more content), we should ensure that browser caching won't result in stale page views.  E.g. on unit_concepts view, I ran search on "foobar" and wrote a new concept definition.  When I returned to this page and ran the same search, I noticed that my brand-new concept did NOT show up in the displayed page.  This turned out to be due to caching.  E.g. if I search on a different search term, now I see my brand-new concept correctly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480184315)

**Comment by maxsocl** [comment]
@cjlee112 yes, we need to tune the cache. Caching is configured in basic configuration now and tuned to all obvious views that need not cache at all. But there are a lot of subtle places where we need to switch off the cache.

**Comment by maxsocl** [comment]
@cjlee112 Because of dynamic nature of our project may be we should move from per-site caching to per-view. In this case we need to mark views that need to be cached but not views that we want to avoid from caching.

**Comment by maxsocl** [comment]
Task on [trello](https://trello.com/c/xzZ9hLsH/201-moving-from-per-site-to-per-view-caching-strategy).

**Comment by maxsocl** [comment]
TODO: still need to add documentation about custom caching strategy
