### ISSUE TITLE
Share courselet (for feedback) before Published

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#713]
Instructors often want to share a courselet with colleagues (to get feedback) without yet making it publicly accessible to students (i.e. Published).  Currently, I think we block all access to a courselet until it is Published.  I suggest that sending an enrollcode directly to another user should give them access to the courselet even if it is not yet Published for all to view.

**Comment by cjlee112** [comment]
Test Share with Tester to see if this addresses the issue fully.

**Comment by rimikt** [comment]
@cjlee112 did you have a chance to test this flow?

**Comment by cmltaWt0** [comment]
I think we can close this.
