### ISSUE TITLE
Old FSM message returns to haunt us after Preview

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#714]
![activity-message-bug](https://user-images.githubusercontent.com/59820/44485328-114b6080-a605-11e8-80a9-100c0ce42304.png)

* clicked Preview for a courselet
* start new chat in Preview
* click Return to end the Preview
* click thread (Answers)
* click "show old UI"

See ancient FSM activity message as shown in attached screenshot.

**Comment by cjlee112** [comment]
This seems to happen if you don't reach the "You have completed the courselet" message in the Preview pane.

**Comment by redilonka** [comment]
checked
