### ISSUE TITLE
IndexError: list index out of range in ul_teach

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#74]
There is a bug in ct/views.py:922 `answer = ul.get_answers().all()[0]`

**Steps to reproduce:**
- Login as a teacher
- Go to course edit page
- Go to a unit edit page
- Start Live teaching session
- Click Next
- Click Next (When you are ready to present the answer to the students, click Next:)

**At this point we get Exception:**

```
Traceback (most recent call last):
File "/Users/thatmax/code/socraticqs2/_ve_socraticqs2/lib/python2.7/site- packages/django/core/handlers/base.py", line 111, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/thatmax/code/socraticqs2/_ve_socraticqs2/lib/python2.7/site-    packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
  return view_func(request, *args, **kwargs)
File "/Users/thatmax/code/socraticqs2/mysite/ct/views.py", line 923, in ul_teach
  answer = ul.get_answers().all()[0]
File "/Users/thatmax/code/socraticqs2/_ve_socraticqs2/lib/python2.7/site-  packages/django/db/models/query.py", line 177, in __getitem__
  return list(qs)[0]
IndexError: list index out of range
```

**Posible way to avoid this next:**

```
- answer = ul.get_answers().all()[0]
+ answer = ul.get_answers().all().first()
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480183929)

**Comment by cjlee112** [comment]
`FSMStack.__init__()` adds any edge whose name starts with `select_` to the set of arguments visible to the HTML template.  The template ct/lessons.html (line 64) is checking for `select_unitLesson` events and adding the button.  To me, this looks like a good case for a plug-in method to customize the behavior.  I.e. we could add a method to our plug-in node like `select_UnitLesson_filter(edge, input)` that would return True if the input is acceptable for this edge.  In the current case it would only accept a UnitLesson input if it were a question...  Then we would have to write a django custom filter that would accept the edge (in this case provided by `fsmStack.select_UnitLesson`) and input (in this case, `ul`) and pass the input forward to the plug-in method.

**Comment by maxsocl** [comment]
Yes, it is a good method to filter input's.
I'll implement and will create a PR.

**Comment by cjlee112** [comment]
@maxsocl Did you add a test for this bug?

**Comment by maxsocl** [comment]
@cjlee112 We have branch with updated tests and I planned add tests for this code and bug there after this PR will merged (to not rebase master again).

**Comment by maxsocl** [comment]
We have added the tests for this bug. But there is one issue with current fix - it filter UnitLesson's to decide to add button or not but not prevent user from clicking on non-question UnitLesson link in Live session mode.
In this case we still can fall into Exception.

To prevent this I propose to change a bit `ul_teach` view:

```diff
-    if pageData.fsmStack.state and pageData.fsmStack.state.isLiveSession:
+    if pageData.fsmStack.state and \
+       pageData.fsmStack.state.isLiveSession and \
+       UnitLesson.objects.filter(pk=ul_id).first().is_question():
         query = Q(unitLesson=ul, activity=pageData.fsmStack.state.activity,
                   selfeval__isnull=False, kind=Response.ORCT_RESPONSE)
         n = pageData.fsmStack.state.linkChildren.count() # livesession students
         statusTable, evalTable, n = Response.get_counts(query, n=n)
-        answer = ul.get_answers().all()[0]
+        answer = ul.get_answers().all().first()
```

**Comment by maxsocl** [comment]
We have added the tests for this bug. But there is one issue with current fix - it filter UnitLesson's to decide to add button or not but not prevent user from clicking on non-question UnitLesson link in Live session mode.
In this case we still can fall into Exception.

To prevent this I propose to change a bit `ul_teach` view:

```diff
-    if pageData.fsmStack.state and pageData.fsmStack.state.isLiveSession:
+    if pageData.fsmStack.state and \
+       pageData.fsmStack.state.isLiveSession and \
+       UnitLesson.objects.filter(pk=ul_id).first().is_question():
         query = Q(unitLesson=ul, activity=pageData.fsmStack.state.activity,
                   selfeval__isnull=False, kind=Response.ORCT_RESPONSE)
         n = pageData.fsmStack.state.linkChildren.count() # livesession students
         statusTable, evalTable, n = Response.get_counts(query, n=n)
-        answer = ul.get_answers().all()[0]
+        answer = ul.get_answers().all().first()
```
