### ISSUE TITLE
Read more link gives 404 Not Found error

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#748]
Preview of the following courselet displays a "Read more" link for the fourth thread (Sequence Alignment Path).  Clicking that Read more link opens a new tab, which displays a 404 Not Found error message.

https://www.courselets.org/ctms/course/4/courslet/111/preview

**Comment by rimikt** [comment]
@cjlee112 This 404 error is produced by wrong link address in URL field.

![screenshot at oct 02 16-57-25](https://user-images.githubusercontent.com/877401/46353277-706cae00-c664-11e8-873c-f1986e503798.png)

**Comment by cmltaWt0** [comment]
Not an issue.
