### ISSUE TITLE
UI may confuse instructors trying to save a new error model

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#750]
When an instructor writes a new error model, immediately below the box where they typed they see a button marked "Add Error Model".  They may think clicking this buttons saves the error model that they just typed.  But this button instead just creates a new empty box for typing yet another new error model.  To actually save what you typed, you have to scroll all the way to the bottom of the page and click "Save".  Adding to the confusion, the Save button is often not in the portion of the page that's visible when the instructor is typing in their error model.

(I myself keep making this mistake, even though I know the whole site backward and forward).

**Comment by cjlee112** [comment]
Our first beta-test instructor complained about being tricked by this too.  We need to fix it ASAP.  Please change the button label to "Start writing a new (blank) Error Model"

**Comment by cmltaWt0** [comment]
Added to the current sprint

**Comment by cmltaWt0** [comment]
Done
