### ISSUE TITLE
EM explanations were not shown at any point in courselet

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#754]
Just tried this preview: https://www.courselets.org/chat/preview/enrollcode/63f045b0c82b406088c7ccf2b1ac5ce2/

I self-assessed every question "wrong" and picked an error model, yet I was never shown a single explanation for any of my error models, even after I finished the courselet.  Nor are they available in the sidebar (see the attached screenshots).  Something is broken!

![no-em-explanation](https://user-images.githubusercontent.com/59820/47535667-6019ae80-d871-11e8-839b-737b6e20f536.png)
![no-em-explanation2](https://user-images.githubusercontent.com/59820/47535668-6019ae80-d871-11e8-844b-f8fb4da3eeb5.png)
![no-em-explanation3](https://user-images.githubusercontent.com/59820/47535670-6019ae80-d871-11e8-8901-db0f99104f19.png)

**Comment by cmltaWt0** [comment]
@cjlee112 Your EM doesn't have any resolutions.

I've added new Test resolution and got an explanation.

**Comment by cmltaWt0** [comment]
Done in 175d0a64961ffbdf0ddccc0120a18178447193ad

TODO: return back from hack to achieve the desired behavior.
