### ISSUE TITLE
Updates for chat UI standard messages

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#756]
Let's make the following changes to the standard messages during student chat:

* "Select the level of your confidence?": change to "How confident are you?"

* "Below are some common misconceptions. Select one or more that is similar to your reasoning.": change to "Here are the most common blindspots people reported when comparing their answer vs. the correct answer.  Check the box(es) that seem relevant to your answer (if any)."

* "Click continue to get additional materials": I don't see why we even need this message, seems like a waste of time. Or change to "Let's address each blindspot."

* when showing title of EM to display explanation, let's add "Re: " before the title.

* "Hope you've overcame the misconception": again, this seems like wasted time.

* "Choose the degree of your understanding": change to "How well do you feel you understand this blindspot now?  If you need more clarifications, tell us."

* "OK, but need further review and practice": too vague; sounds too similar to "need more help".  Change to "OK, but flag this for me to review".

  If the student said "still confused", insert message "We will try to provide more explanation for this."

* "You've finished resolving previous Unit.": change to "OK, let's continue."

**Comment by cmltaWt0** [comment]
@cjlee112 

Changed all points except of the following:

- If the student said "still confused", insert message "We will try to provide more explanation for this." [this will be changes in scope of another task]


- "Hope you've overcame the misconception": again, this seems like wasted time [this will be changes in scope of another task]

"Click continue to get additional materials": I don't see why we even need this message, seems like a waste of time. Or change to "Let's address each blindspot." [changed text for now] [will be removed later - will add new task]

**Comment by cjlee112** [comment]
@cmltaWt0 We need to finish releasing these changes, as beta testers are complaining that these messages are confusing: "Hope you've overcame"; "You've finished resolving previous Unit."; lack of message "We will try to provide more explanation for this."

We should also insert a message after displaying the answer: "How close was your answer to the one shown here?"

**Comment by cmltaWt0** [comment]
Added to the current Sprint.

**Comment by cjlee112** [comment]
@cmltaWt0 According to CR-424691 you implemented in the current release a New FSM adiitional node to add message with the text 'We will try to provide more explanation for this.'  However, this message is NOT displayed on staging, as shown in the attached screenshot:
![screenshot at 2019-01-31 13-58-20](https://user-images.githubusercontent.com/59820/52088445-b37e5580-2560-11e9-9f42-13903a4024da.png)

**Comment by cmltaWt0** [comment]
@cjlee112 It is implemented.
This message would be shown in case Student say `Need help` and there is another Resolution to display.
If it is nothing to provide right now to resole the misconception - I didn't show this message.

Basically it was implemented in a way you probably want (as far as I can see after you message) - this message appears each time a Student answer `Need help`. But later I changed the behavior to not post this message after the last Resolution.

**Comment by cjlee112** [comment]
@cmltaWt0 If there are NO Resolutions, we need to display the message "We will try to provide more explanation for this."  The whole intent of our system is that if there are students who are still confused, the instructor will provide more explanation.

**Comment by cmltaWt0** [comment]
@cjlee112 As far as I can see - we need to revert our logic :)
Display this message only it there are no resolution left for the current EM.

**Comment by cjlee112** [comment]
@cmltaWt0 To keep things simple now, can we ONLY display "We will try to provide more explanation for this" if there are ZERO resolutions?

**Comment by cmltaWt0** [comment]
Yes.

**Comment by cjlee112** [comment]
Or do you prefer your proposal "Display this message only in case there are no resolutions left for the current EM"?  That sounds fine to me too

**Comment by cmltaWt0** [comment]
:) I prefer second option.
It will cover first option (display the message when there are no resolution at all) and second one.
Effort will be almost the same to change the logic.

**Comment by cmltaWt0** [comment]
@cjlee112 I've changed behavior.
Could you check it on staging?

**Comment by cjlee112** [comment]
@cmltaWt0 Now fixed on staging. Looks good!
