### ISSUE TITLE
Fix inconsistent links for REST formatting tips

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#769]
Courselets is showing inconsistent links for REST formatting help, on the sidebar (e.g. in student Chat or preview) vs. on the Edit Thread page.  They should both be changed to point to our new formatting tips on Help Center (Intercom): https://intercom.help/courselets/getting-started/formatting-basics-with-restructuredtext

**Comment by cmltaWt0** [comment]
Added to the current Sprint.

**Comment by cmltaWt0** [comment]
Fixed
