### ISSUE TITLE
Pypandoc and md2html overload

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#77]
## Issue

Template tag `md2html` is used on every page where we need to convert `rst` text to `html` MathJax.
So we need to avoid this duplicate work.
## Proposed solution
1. We can use django caching system to cache exactly  `md2html` template tag on every page - need to decide time for cache expire time.
2. Add additional fields to all models with auth rest text to convert on save signal rest text to html and use this html text on all fields.
3. Without additional fields in DB - we using django template tags caching with TIMEOUT = None and updating cache on save action.

Task on [trello](https://trello.com/c/ZGYdkI1W/202-avoid-calling-md2html-template-tag-in-every-page-with-rest-text).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480183673)

**Comment by maxsocl** [comment]
@cjlee112 

Notes after discussion
------------------------------
 * Memcached is not appropriate backend to place big amount of data
 * Consider to use DB field as a storage of converted text.
 * Consider to use file based cache backend as s storage of converted text.

Pros of using file based cache storage
---------------------------------------------------
 * In case of migration data to another server there is not need to move increased DB with duplicated fields - we simply backup DB and don't aware of file based cache.
 * There is not RAM constraint against memcached.

Alternative implementation will be provided for discussion and this issue will be updated.

**Comment by maxsocl** [comment]
@cjlee112 

There are two different implementations to discuss:
  1. DB implementation - https://github.com/raccoongang/socraticqs2/commit/916dbf02fb6d6a222c9a93f90519b32e8ce92282
  2. File based cache implementation - https://github.com/raccoongang/socraticqs2/commit/4d4791dcff20e3396983013ebb0e794a5a72112b
 
Third implementation using memcached is rejected as inappropriate for large amount of data to cache.

**Comment by cmltaWt0** [comment]
Decided to pre-convert text in the special field.
