### ISSUE TITLE
Full-screening an onboarding video traps the user with no (visible) way to get back to Courselets

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#770]
I observed this problem in Firefox 64.0; don't know if it happens in other browsers.  If I fullscreen a video during Onboarding, when the video ends I'm shown a choice of "More Videos from Christopher Lee" and a few Vimeo buttons (Like, Share, Replay) but no way to exit full-screen mode and get back to Courselets.  Even if the user knows to press the Escape key to get out of this "More Videos" view, that still leaves them in full-screen mode -- they then have to know to click on the x in the upper-right corner.

Seems like Vimeo probably provides some way to ensure that a one-click exit-fullscreen control gets shown?

Could this bug also happen to students who watch a video within the Chat UI?

**Comment by cjlee112** [comment]
if there's no way to avoid this problem within Vimeo, we could of course move the onboarding videos to a different streaming service.

**Comment by cmltaWt0** [comment]
Added to the current Sprint as an investigate ticket.

**Comment by cjlee112** [comment]
@cmltaWt0 Have you found a workaround for this using Vimeo?

**Comment by cmltaWt0** [comment]
@cjlee112 Yes. We will try add the same control as original Vimeo player has.
This is not default behavior for Vimeo Embedded videos. 

<img width="1679" alt="screenshot at jan 29 17-37-01" src="https://user-images.githubusercontent.com/877401/51919708-ae989500-23ec-11e9-8867-40ce7b0cfc88.png">

The Exit button should add more transparency for how to exit this fullscreen mode.

**Comment by cjlee112** [comment]
@cmltaWt0 I actually want an absolutely minimalist UI behavior when the video finishes.  I do not want any distracting controls such as Like, Share bla bla bla:

- the best option would be to have the full-screen video **just close automatically** when the video finishes playing, i.e. exit from fullscreen so the user just sees the onboarding page that launched the video. This is best because the user does not have to do anything to continue with the onboarding, and there is no possibility of getting pulled off-track from the onboarding.

- if there is no way to make fullscreen video exit automatically, the next best option would be for it to show only a single, large button that closes fullscreen mode, returning the user to seeing the onboarding page that launched the video.  Again, there should be NO other possibilities that could pull the user off-track from the onboarding.

- if there is no way to completely get rid of buttons such as Like, Share, the key thing is that there must be no buttons that lead to a different video or page.  For example, there should be NO "up-next" video or "other videos by Christopher Lee" or other such nonsense.  The user should only have one next step from this fullscreen mode, namely to close the fullscreen mode and return to seeing the onboarding page that launched the video.

- if there is no way to completely get rid of "up-next" / "other videos by Christopher Lee" then I think we have to switch to a different streaming service (instead of Vimeo) as we cannot afford injecting anything that deliberately tries to pull our users away from the onboarding!

**Comment by cjlee112** [comment]
@cmltaWt0 By the way, all the concerns that I have raised here apply equally well to non-fullscreen mode: once the video finishes the player must NOT show any "up-next" / "other videos by Christopher Lee" etc. distractions that could pull users away from the onboarding.

**Comment by cjlee112** [comment]
@cmltaWt0 Apparently vimeo's player API supplies an event ("ended") that's triggered when the video ends, see the docs: https://github.com/vimeo/player.js#embed-options
Here's an example of using it: https://elearning.adobe.com/2017/12/end-of-video-events-with-vimeo/

**Comment by cmltaWt0** [comment]
@cjlee112 We can configure After Play action easily.
I have no access to Vimeo account so I thought you reject this way (to close fullscreen automatically).

**Comment by cjlee112** [comment]
@cmltaWt0 Staging is still broken exactly as last production release was, I'm attaching a screenshot.  We need to talk about how you are planning on fixing this issue in this release.

**Comment by cjlee112** [comment]
![screenshot at 2019-01-29 14-54-44](https://user-images.githubusercontent.com/59820/51946427-4fc82100-23d6-11e9-8c61-eb2cb09fe5bc.png)

**Comment by cmltaWt0** [comment]
@cjlee112 The fix is not applied on staging or dev.
I want to handle the playback end event to trigger exitFullScreen event for browser.

**Comment by cjlee112** [comment]
@cmltaWt0 Thanks, I changed the embed settings for all the onboarding videos on Vimeo to hide Like, Share, etc.

**Comment by cjlee112** [comment]
@cmltaWt0 Not sure what's going on but I just re-tested this on staging (forced my browser to reload the onboarding page from staging) and I still see exactly the same problem ("More videos from Christopher Lee", see attached
![screenshot at 2019-01-30 10-07-36](https://user-images.githubusercontent.com/59820/52002558-362ae600-2477-11e9-8f84-6ce5eb7c0435.png)
).  Argh.

**Comment by cmltaWt0** [comment]
@cjlee112 I've added additional handler to exit full screen mode after Video end.
Did it what you want?
So we removed one additional click for Instructors to return back to the onbording page. 

On case we want completely avoid any interactions for Instructors I can close Vimeo player completely on video end event. 

Also final screen (More video from Chris) can be configured in Video dashboard in embed presets section.

**Comment by cmltaWt0** [comment]
@cjlee112 Done. Will be deployed on https://dev.courselets.org in a 20 mins.

**Comment by cjlee112** [comment]
@cmltaWt0 Thanks for telling me about After Video presets in Vimeo dashboard.  I changed it to get rid of "More from Christopher Lee" on all our onboarding videos.  I think we have now fixed this issue!

**Comment by cmltaWt0** [comment]
@cjlee112 :) I've just uploaded a fix.

New behavior - Video player closes immediately after playback ends.

Can you check the new behavior on https://dev.courselets.org ?

**Comment by cmltaWt0** [comment]
If it is ok for you - we can use this behavior and move it to the staging.

**Comment by cmltaWt0** [comment]
Also it is currently on https://staging.courselets.org too just for test

**Comment by cjlee112** [comment]
@cmltaWt0 Unfortunately I just found another place (Create a Courselet page) on staging where it is not automatically closing the viewer when the video ends, as shown in the attached screen shots:
![screenshot at 2019-01-31 12-50-33](https://user-images.githubusercontent.com/59820/52084566-37cbdb00-2557-11e9-8cce-f65cf376d735.png)
![screenshot at 2019-01-31 12-51-28](https://user-images.githubusercontent.com/59820/52084567-38647180-2557-11e9-961e-e8deb312b097.png)

**Comment by cmltaWt0** [comment]
It was done only for Onboarding page.

If it is desired to has the same behavior everywhere in Instructor UI - will do it quickly.

**Comment by cjlee112** [comment]
thanks, please fix this page.  This page is in fact part of the default Onboarding flow.  I hit this simply by clicking the steps shown on the Onboarding page.

**Comment by cmltaWt0** [comment]
I understand. Just my impression was to enforce this auto-close only for main on-boarding.
Going to apply for another pages.

**Comment by cjlee112** [comment]
Same issue on the Courselet Add Threads page, e.g. https://staging.courselets.org/ctms/course/69/courselet/84/units

**Comment by cmltaWt0** [comment]
@cjlee112 Fixed. Please check.

**Comment by cjlee112** [comment]
@cmltaWt0 fixed on both Create a Courselet and Add Threads pages.  thanks!
