### ISSUE TITLE
Incorrect instructions on Abort Thread

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#772]
At the bottom of the Edit Thread page we currently have "Abort Thread: Enabling this will allow your students to skip directly to the error models without submitting an answer."  This is totally incorrect.  Please change this to "Offer help for meta-blindspots (What are meta-blindspots? LINKED to https://intercom.help/courselets/getting-started/what-are-meta-blindspots)

**Comment by cmltaWt0** [comment]
Added to the current Sprint.
