### ISSUE TITLE
Display user's initials if no avatar picture available

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#774]
This is a subcase of issue #773, to display the instructor's initials and student's initials next to their chat messages, instead of a blank avatar.

**Comment by cjlee112** [comment]
I like @karluxd design using dark vs. light backgrounds to distinguish instructor vs. student:
![image](https://user-images.githubusercontent.com/59820/52810909-92316500-3048-11e9-9359-1a0d41a3c955.png)

**Comment by cjlee112** [comment]
@karluxd RE: your question about whether we will always have names for student and instructor, I believe so.  Just in case we do not, I suggest displaying the following defaults if the name is missing: "you" (for student messages); "instructor" (for instructor messages)

**Comment by cmltaWt0** [comment]
@cjlee112 Did you mean `Y` and `I` for you and instructor? We can use up to two characters to fit in square.

**Comment by cjlee112** [comment]
@cmltaWt0 If we're limited to just two characters, I suggest "me" (for student messages) and "Pr" (for Professor messages)

**Comment by karluxd** [comment]
We could also have two different avatars as a backup if the name is missing. What do you think?

![student course courselet no name 2x](https://user-images.githubusercontent.com/241800/52853645-83b47d80-311c-11e9-9a6c-acee4a70f96c.png)

**Comment by karluxd** [comment]
@cmltaWt0 just replace lines 301–309 in https://github.com/cjlee112/socraticqs2/blob/master/mysite/lms/static/sass/student/components/_chat.scss with this:

```
.chat-avatar {
  display: inline-block;
  width: 44px;
  height: 44px;
  border-radius: 4px;
  box-shadow: 0 0 1px 0 rgba(0,0,0,0.3), 0 1px 3px 0 rgba(0,0,0,0.12);
  border: none;
  font-size: 19px;
  font-weight: normal;
  line-height: 44px;
  text-align: center;
}

.chat-avatar--instructor {
  background: #1E1A34;
  color: #F5F8FA;
}

.chat-avatar--student {
  background: #FFFFFF;
  color: #1E1A34;
}

.chat-avatar--image {
  background: #FFFFFF;
}
```

**Comment by karluxd** [comment]
HTML:

```

**Comment by cjlee112** [comment]
@karluxd @cmltaWt0 I think we can get the best of both worlds by combining our different ideas for how to deal with the no-name case:

- if we have no name for the student, use the string "me"
- if we have no name for the instructor, use the generic-avator icon (i.e. the icon we are currently using on production)

Also, we should always (regardless of whether we are displaying initials or an icon) use dark background for student (to match the darker background we have always been using for student chat messages), and light background for instructor.  Note that this is the opposite of the two screenshots above.

**Comment by cjlee112** [comment]
@karluxd @cmltaWt0 The reason I like using "me" for the student is that it makes it absolutely clear who is speaking, whereas the icon does not.  Actually, the more I think about this, I think it would be clearest and simplest to use "me" for the student ALWAYS, instead of the student's initials.

**Comment by cjlee112** [comment]
@cmltaWt0 @redilonka Note that I specified the lower-case string "me", but you have changed it into ALL-CAPS "ME".  This is strange and undesirable.  Whereas "me" is obviously not someone's initials and hence is clearly the first-person-singular pronoun, "ME" looks like it must be someone's initials ("Maxwell Edison" of Maxwell's Silver Hammer?), or even weirder someone shouting "ME!" in ALL-CAPS.

**Comment by cmltaWt0** [comment]
@cjlee112 Done.
Please not that this implementation was presented in notion via screenshots one week ago and everybody agreed with this implementation.
https://www.notion.so/Feb-2019-Release-a1d1d5d8dce34a53a1265203cc419bcd#52736becd4ab4f43a15d717c569065af

**Comment by cmltaWt0** [comment]
So now implementation doesn't much the specification.
@redilonka please change specification to be identical with this change.
