### ISSUE TITLE
In the courselet 'Settings' tab, the checkbox is not on the left of its text.

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#775]
**PRECONDITIONS**
you need to have a registered account or a Google account to log in;
to register a new account go https://dev.courselets.org/signup/?next=/ctms/

**STR**

go https://dev.courselets.org/ctms/
log in with your Google account or with email
click 'Create Course'
input your course name into the 'Course Name' field, for example, 'Test Course'
click the 'Create Course' button
click 'Create Courselet'
input the course name into the 'Course Name' field, for example, 'Test Courselet'
click the 'Create Courselet' button
go to the courselet 'Settings' tab
AR: the checkbox is not on the left of its text
ER: the checkbox is on the left of its text

**Comment by redilonka** [comment]
fixed
