### ISSUE TITLE
can't add answer for resolution ORCT

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#780]
An instructor wants to be able to give follow-up question(s) as resolutions for an error model, but when they do so (only possible in the old instructor UI), the ORCT is created but there is no way to add an answer (the user is not prompted to enter an answer, nor is there a Answer tab shown).

**Comment by cmltaWt0** [comment]
Answer tab added. The behavior for ChatUI remains the same - Lesson text presented as usual brief definition.
