### ISSUE TITLE
Send an Intercom event for creating a courselet etc.

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#782]
Presumably we would use Intercom's REST API or Javascript.  The first place to add this would be onboarding stages such as completing the intro courselet (step 2), creating a courselet, adding a thread.  Here are the intercom docs on how to do this:
https://www.intercom.com/help/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/set-up-event-tracking-in-intercom

**Comment by cjlee112** [comment]
@cmltaWt0 Could you estimate how much effort this would take, to report a couple basic events (e.g. a couple onboarding steps) to Intercom.  Specifically, is there any possibility of including this in our current (Feb 2019) release?

**Comment by cjlee112** [comment]
@cmltaWt0 I decided we do not need this for the Feb 2019 release.

**Comment by cmltaWt0** [comment]
ENV: DEV

**Comment by cmltaWt0** [comment]
## Events we could report

- **step-completed**: completed an onboarding step
- **orct-created**: created new ORCT: report total count as data attribute "ORCT written"
- **invitation-sent**: invited tester
- **courselet-published**: published Courselet
