### ISSUE TITLE
"Switch to the old Instructor UI" sounds too drastic

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#784]
In English, "switch" implies a **permanent** change, whereas what we really mean is merely offering the user a temporary way to view the old UI.  I suggest changing this phrasing to "View the old Instructor UI if you want to add resolutions."

**Comment by redilonka** [comment]
@cmltaWt0 I see that phrase was renamed but not the same as Chris said.

in Answers --> threads --> You can find additional features in the old Instructor UI.
create new thread --> You can also search Courselets for exercises to add, using the old Instructor UI.

**Comment by redilonka** [comment]
done
