### ISSUE TITLE
My Courses ignores instructor Role object

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#795]
Access privileges to course materials are governed by the Role object.  For example, for a user to be granted Instructor privileges (e.g. editing) on a Course, we create a Role object for them with type Instructor, pointing to this course.  However, I just noticed that this doesn't seem to work properly in the new instructor UI (ctms).  Specifically, even though I created an instructor Role for user jaia on course "LS30 Materials prep", it does not appear on her My Courses list, and gives an error message if she tries the preview URL I gave her.  I see the same behavior using my foobaron account, if I change the course's addedby field to anyone other than myself.  This breaks our ability to associate more than one instructor with a course.

**Comment by cjlee112** [comment]
@cmltaWt0 @redilonka 
![error404](https://user-images.githubusercontent.com/59820/63131132-87ad4500-bf71-11e9-8401-dbe2cb6e03d7.png)
One more aspect we should make sure to check in QA: when UnitLesson has addedBy set to someone other than the current user, clicking the edit link for that thread gives a "Not Found" error message (on current Production server; see attachment), even if the current user "owns" both the course and courselet (via addedBy field on those objects).  Again, this "Not Found" behavior is both misleading (assuming the server should deny permission to edit, the error code should be Access Not Allowed), and incorrect according to our permissions model (i.e. if current user has Role=Instructor on this course, they should be allowed to edit a thread, even if they didn't initially create that thread).

**Comment by cmltaWt0** [comment]
@cjlee112 The fix was implemented and deployed on the development instance. It is not currently released. I can do it today. Will let you know about the release.

**Comment by redilonka** [comment]
Instructor Roles fix has been deployed on production.
