### ISSUE TITLE
Need instructor UI for accessing alternate versions of a lesson

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#97]
_Background_: In its internal data structures, Socraticqs2 already keeps a full "version control commit tree" of lessons.  In its UI, it provides a simple mechanism for users to commit a version snapshot (by providing a commit message), and having the same lesson in different courselets provides a natural equivalent to _git branch_ (i.e. each courselet is a separate branch).  

However, at present there is no UI for allowing the user to specify _which_ version of a given lesson s/he wants.  For example, back when I implemented search results for lessons, I felt that it would be confusing to see alternate versions of the same lesson in the search results.  So the search results are filtered for distinct treeID (all lesson versions derived from a common ancestor share the same treeID).  (I should also point out that the search results will only return a "HEAD" version currently being used in a courselet, never an older, deprecated version; see UnitLesson.search_text() for details).  However, this is already becoming too limiting; for a given lesson I want version X and the search results are giving me version Y, and no way to choose X instead.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480186300)

**Comment by cjlee112** [comment]
Note that even now there is a simple workaround for this issue, consisting of two pieces of information:

1. in a courselets URL, the lesson ID (following `/lessons/` in the URL) identifies the specific version used in that courselet.
2. if you append a lesson ID to a different courselet (i.e. that does not contain that lesson), the UI will automatically offer you the option: "This lesson is not part of this courselet. You can add it to this courselet by clicking the Add button below."

This provides a way to add exactly the lesson version you want.

**Comment by cjlee112** [comment]
That would also make it very easy to provide a simple UI for choosing between alternate versions.  All we'd have to do is add a Versions tab to the lessons tabset.  This view would simply run a query for UnitLessons that share the same treeID but point at a different lesson version, and display a table of git-log style info about them (such as commit author, commit message, time stamp, courselet (which is equivalent to branch), with a link that simply appends the lesson ID to the current courselet URL.  Clicking that link would work exactly as described above (with no changes required to our existing code), i.e. display that specific version with the usual option: "This lesson is not part of this courselet. You can add it to this courselet by clicking the Add button below."

**Comment by cmltaWt0** [comment]
Implemented
