### ISSUE TITLE
"temporary user" access only possible via course_subscribe view

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#98]
Our login process is supposed to allow visitors to "try out" the site without having to go through a standard account creation process; even entering an email address is supposed to be optional, i.e. you can work on courselets even before clicking the email validation link.

However, it looks to me like that actually doesn't work in general (i.e. any view with login_required decorator).  The `psa.custom_login` view forces users to enter an email address, and does not allow them to proceed to their desired view (in my testing, anyway).

There is only one view that appears to support the intended design (create a Temporary User login and invite them to optionally enter an email address): `courses_subscribe`.  

I think several changes are needed:
- the Temporary User creation code should be moved out to somewhere more general, e.g. psa utilities.
- `psa.custom_login` should make use of that Temporary User creation mechanism.
- we should create a classmethod `Role.get_or_enroll(user, course)` that properly checks whether the user is already enrolled in the course per issue #93.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480187717)

**Comment by karlwho** [comment]
Opening up lessons to unregistered users makes content shareable, i.e. you can easily recommend a specific lesson which will help us recruit new users, and new users can browse any material that will further convince them to sign up.

I have been thinking about where it would make most sense to draw the line for a guest user. While it could be useful for them to complete an ORCT without an account, I would argue that they are highly motivated to create an account after answering a question. So what I propose is that guest users can browse all passive lessons, and that they can enter an answer in ORCT’s but are asked to sign up when they try to post their answer.

Avoiding duplicate enrollments is definitely a good idea. What I will propose in an upcoming wireframe is that we add a button to each course that says either “Enroll” or “Leave”. That means the course would still be visible under public courses but you can not enroll twice. Think of it as follow/unfollow on Twitter.

**Comment by maxsocl** [comment]
> The psa.custom_login view forces users to enter an email address, and does not allow them to proceed to their desired view (in my testing, anyway).

`psa.custom_login` view checking login/pass from user on POST request and rendering `custom_login.html` on GET request.

**Comment by maxsocl** [comment]
> psa.custom_login should make use of that Temporary User creation mechanism.

I agree with this. So every decorated by `login_required` view can be accessed without signing up.
So we need to ask user to continue via Temporary session or login as a Regular user.
So we need to decide how to ask user this question.

**Comment by maxsocl** [comment]
> we should create a classmethod Role.get_or_enroll(user, course) that properly checks whether the user is already enrolled in the course per issue

Ok. Couple of questions:
1. Do we handle `Enrolled Student` and `Self-study`  as the same Roles but leave both to be available to create? So if student was enrolled as `Self-study ` then LTI user simply use this role and vice versa?
2. How should we handle `Instructor` and `Teaching Assistant`? Does user can enroll as an Instructor only via LTI or we need to implement enrollment as a Instructor/Teaching Assistant too?

**Comment by cmltaWt0** [comment]
Current Student UI doesn't allow us to use Anonymous access. So let's close this fo now.
